# PART I. {.unnumbered}

## Origin of Divided Protestantism
When Luther in Germany opposed Roman Catholicism and popery, it was because the Roman Church had perverted the Gospel of Christ, taught righteousness by works, and prohibited the circulation of the Bible among the people.  Strive as he would, his troubled soul could find no consolation in following the precepts of the Church.  It was only after years of fruitless toil, in and out of the cloister, that he had at last found peace and consolation in the precious promise of the Lord:  "The just shall live by his faith" (Hab. 2, 4)

The Swiss Reformers, Calvin and Zwingli, on the other hand, do not seem to have been thus troubled.  Though earnest in their reform work, they worked more in the direction of emancipating their Churches from the yoke of the Roman organization, in eradicating superstition, correcting outward, flagrant abuses, and instilling into the minds of the people a spirit of independence, political as well as religious.

Luther contended that an effectual reformation must come from within; for if the tree is made good, the fruit will also be good.  The Swiss made the branches, instead of the root, their point of attack.

Luther's weapon in the battle of the Reformation was the Word of God only.  With this means, he said, the Savior repelled even Satan himself.  With this means the apostles conquered the heathen world and laid it at the feet of Christ.  To the Swiss this method was too slow; they were not content with letting the leaven of the Gospel work in its peculiar way; they must needs also use physical force and political power, a trait to this day characteristic of the Reformed Church.

Closely allied to this was the different views taken by the Reformers as to the value of the Scriptures.  Luther contended that the Word of God was not merely a message to mankind, but the vehicle of the Holy Spirit through which He gives the proffered grace, a truth attested by the Apostle Paul, when he says that the Holy Spirit was given through the preaching of the Gospel (Gal. 3, 2), and faith through the Word of God (Rom. 10, 17).

Zwingli, on the other hand, believed that the Spirit needed no means, that He worked independently of the Scriptures.  The preaching of the Word was to him only "an outward sound," outside of which the Holy Spirit must work regeneration and salvation.  Hence, he hoped "that good men in all ages, who had walked uprightly according to the light they had, were also saved." (_Expos. Fidei_, 2, 559.)

But the real difference between the Reformers came to light in their discussion concerning the authority of the Scriptures.  Luther contended with the Apostle Paul that the natural man receiveth not the things of the Spirit of God, for they are foolishness unto him, neither can he know them, because they are spiritually discerned.  (1 Cor. 2, 14)  Hence, if he would not be adjudged wise in his own conceit (Rom. 12, 16), he must not think above that which is written (1 Cor. 4, 6), but bring into captivity every thought to the obedience of Christ (2 Cor. 10, 5).  History as well as his own experience had taught him that it was futile to worship God, teaching for doctrines the commandments of men (Matt. 15, 9), and therefore he set up this formula in the Smalcald Articles:  "It is certain that the Word of God alone shall set up articles of faith, and none else, not even an angel."  (II, 15.)

No doubt, the Swiss would have said Yes and Amen to this, adding the rationalistic phrase:  "rightly understood."  (John Calvin declared that he had signed the Augsburg Confession in this manner.)  They did not deny the authenticity of any part of the canonical Scriptures, but ever and anon they would follow human reason, and assert that the language of the Holy Spirit must not be taken in a literal, but in a figurative sense, as, for instance, in the doctrine of the Lord's Supper.  Any other interpretation, they said, would be "absurd" and "unreasonable."  What becomes of the Scriptures under such treatment we shall observe as we enter more fully into our subject.

That such opposite views concerning the Scriptures should be followed by Different methods of church-work is not surprising.

To Luther only such changes seemed necessary as would promote true piety.  Any ceremony, therefore, which had come down from antiquity, and was not connected with any idolatrous practice, or could be cleansed from such, was retained.  Church interiors, with altars, pulpits, sacristies, organs, paintings, and statuary, were retained, also clerical vestments and the observance of many holidays; in short, anything and everything which could be used properly, and was not prohibited by the Word of God.  

To the Swiss everything Catholic was "a heathenish abomination."  What the Scriptures did not directly command was to them unscriptural, and hence they not only countenanced the ruthless destruction of statuary and paintings in churches, but even counseled to do so.  Church interiors were entirely remodeled, and ceremonies of the most simple kind instituted.  This difference between the Reformed and the Lutheran position may best be illustrated by an anecdote.  In discussing the retention or rejection of the old liturgies, Zwingli said, "Show me a passage in the Scriptures wherein they are enjoined."  To which Luther replied, "Show me a passage wherein they are condemned."  

The different stand taken by the Reformers concerning Church and State must not be overlooked.  The Lutheran Church soon became a State Church, it is true, but in spite of the teachings of Luther.  "It is with the Word we must contend," he observed, "and by the Word we must refute and expel what has gained a footing by violence.  I would not resort to force against such as are superstitious, nor even against unbelievers!  Whosoever believeth let him draw nigh, and whoso believeth not, stand afar off.  Let there be no compulsion.  Liberty is of the very essence of faith.  God does more by the simple power of His Word than you and I and the whole world could effect by all our efforts put together!  God arrests the heart, and that once taken, all is won."  

To the Swiss Reformers the Jewish Church of the Old Testament was the only correct model.  Zwingli looked upon the Council as representative both of Church and State, and the theocratic State Church organized by Calvin at Geneva is a fact well known to all students of history.  Even in America the Reformed Church commenced as a State Church, and the roots of it are still sprouting such shoots as Sunday-laws, chaplains for conventions, Congress, legislatures, and for the army and navy, and the fanatical activities of the National Reform Association.

The Reformed Churchis split up into a multitude of sects.  They have no confession to which they all subscribe; many of them have no confession at all, and others modify their beliefs as occasion demands.  This is because a belief founded partly on "reason," "views," "science," "feeling," and the like, can have no stability.  Views change; the rational way of one is irrational to another; the science of to-day is a fable to-morrow.  In order, therefore, to gain recruits for this or that sect, innumerable schemes, methods, and measures are resorted to, -- camp-meetings, revivals, the Y. M. C. A., and of late the Laymen's Movements, Sociali Service, etc.

We shall now pass in review the principal denomination which have a following in the United States.  Our next chapter briefly summarizes the history of these denominations, and succeeding chapters will take up, one at a time, the chief doctrines of Scripture, stating the agreement of our Lutheran Confessions with the same, and the differences which exist between us and the various denominations.

## Historical Summaries
### THE ANGLICAN CHURCH
Many dignitaries of the Anglican Church do not, at the present time, like to date the beginning of their denomination from the time of the Reformation.  And some would like to ignore the Reformation altogether.  Says one:  "England has never had but one religion; it has never changed that religion, and it has that religion still."

From the sixth century until the year 1534, when Henry VIII was refused the sanction of the pope to a divorce from his first wife (he had six in all), England was as much a Catholic country as any other of the European states.  In that year, to avenge himself on the pope, Henry "denied the papal supremacy, and declared himself to be the one protector of the English Church, its only and supreme lord, and, so far as might be by the laws of Christ, its supreme head."  And this Parliament later confirmed.  This was the beginning of the revolt which carried England outside the Catholic fold.

Writings of Luther and, later, of the Swiss Reformers were early and eagerly read in England.  Henry, who had written against Luther before the breach with the pope, continued in the Church, and, as far as Roman doctrine is concerned, died a Catholid; but when his son, Edward VI, ascended the throne, in 1547, reform ideas were so well rooted that Archbishop Thomas Cranmer, counseled mainly by Reformed theologians (Martin Bucer, Peter Martyr), in 1552 set up a confession of faith containing forty-two articles, later cut down to thirty-nine at the Synod of London, in 1562.  This confession was ratified by Parliament in 1571, and thereby became a part of the law of the land.  "The Book of Common Prayer," which is still in use, contains not only this document, but also a full ritual for all occasions during the church-year.

The Thirty-nine Articles, the confession of the Anglican Church, are decidedly Reformed in tone and tendency, though in many respects taking a middle course between the Lutheran and the Reformed.  But when Episcopal missionaries say to Lutheran immigrants that their Church is the Lutheran, excepting the language, they ought to know that they are not telling the truth.  The Episcopal Church in the United States is only the Anglican Church without state-connections.  It is officially known as The Protestant Episcopal Church.  As such it dates from 1787, when it received its first bishop, Dr. Seabury, and constituted itself independent of England.

In 1873, it suffered a small loss through a few priests, who left it on account of a ritualistic (Romish) tendency, which was rapidly gaining ground in the Church.  They reduced the confession to thirty-five articles, and changed a few expressions here and there.  They are known as The Reformed Episcopal Church.

Though composed of three more or less antagonistic elements, the "high," the "low," and the "broad," the Episcopal Church has escaped any serious division, and has remained virtually one united Church up to this time.  It is governed by bishops, -- hence its name, -- and believes in the so-called Apostolic Succession, an invention inherited from popery.

In late years the Episcopal Church has become very lax in many ways.  Higher criticism and rationalism dominate its theologians, and ritualism opens the way back to Rome for many every year.

In many Episcopal churches, both in our country and in England, prayers are said for the dead, the saints are worshipped, mass is read, and auricular confession to the priest is practised.  Indeed, nothing but the claims of the supremacy and infallibility of the pope seems to stand in the way of a large section of the Episcopal Church going bodily into the Roman Catholic communion.

### PRESBYTERIANS
The attitude of Henry VIII to the REformation, the instability of the government under his first successors, and the double influence of Lutheran and Reformed theologians during the stirring times of the sixteenth century did not allow the English people to study the problems of the Reformation properly.  They were not only continually crossing the English Channel to and fro on account of persecutions of one kind or another, but they were also "tossed hither and thither by all sorts of winds of learning," and as "it is ever to the injury of essentials that the midn of man is preoccupied with secondary matters," the English church people suffered on this account more than any other nation.  "Dissenters," "Independents," and "Non-conformists," and "Puritans" are names which remind the serious-minded Evangelical Christian of to-day of the futile and unnecessary strifes of centuries ago in England, religious, of course, in a way, but mostly about ceremonies, vestments, church furnishings, and church government.

The principles underlying Presbyterianism came originally from Geneva, where John Calvin held sway in Church and State.  This cold, unbending, and rigoristic reformer had patterned his church government mostly on Old Testament lines, and, through strict discipline, sought to attain, if possible, an immaculate Church on earth.  Through John Knox, the Scotch reformer, these and other Calvinistic peculiarities were transplanted on English soil, where they not only became the source of endless troubles, but also the cause of an un-evangelical rigorism and persecutions.

Presbyterians are called so on account of their mode of church government.  When a church is organized, a board of elders is chosen.  The elders elect the minister, and these, called a "session," rule in all temporal as well as spiritual affairs.  Over the session, as a court of appeals, is the presbytery, composed of churches within a given area; a number of presbyteries make up a Synod, a still higher court, and the General Assembley, which meets every three years, constitutes the court of last resort.  

But the Presbyterian Church has also been noted for its Calvinistic doctrine concerning predestination, the belief according to which God has loved, not the whole world, as Christ explicitly declared (John 3, 16), but only a few, namely the elect.  To their Westminster Confession, adopted in 1647, a "declarative statement" was added a few years ago, which, to some degree, softens the language employed in the confession, but as the old confession still stands, the situation is practically unchanged.

The Presbyterians are divided into numerous sects.  A few may be enumerated:  "The Associated Presbyterian Church"; "The Reformed Presbyterian Church " (Covenanters, Cameronians); "The Associate Reformed Presbyterian Church"; "The United Presbyterian Church"' "The Cumberland Presbyterian Church," etc.

Some of the questions which divide these Presbyterian church-bodies are altogether trivial.  The Southern Presbyterians and the United Presbyterian Church, for instance, remain separate mainly because they cannot agree on the question whether any hymns outside of the metrical versions of the Psalms should be sung in public worship.  While the Southern Presbyterians use hymns and "Gospel songs," The United Presbyterians restrict themselves to the use of the Psalms, in agreement with the strict Zwinglian idea that "nothing is permitted except what the Bible commands."  The correct, Lutheran, doctrine on this point is that only that is prohibited which the Bible forbids, and that all else is a matter of Christian liberty, and must not keep the Churches separate.

### CONGREGATIONALISTS
It is a question whether Congregationalists may properly be called a denomination, as the different churches of this body have nothing in common but the name.  

When Congregationalists maintain, "That every Christian church is entitled to elect its own officers, to manage all its own affairs, and to stand independent of, and irresponsible to, all authority, saving that only of the Supreme and Divine Head of the CHurch, the Lord Jesus Christ," they so far utter a precious Scriptural truth.  But when they condemn the formation of even _advisory_ church-bodie (synods), the acceptance of a common confession or creed by such bodies, and when in the confessions of their several local churches they sometimes use terms so vague that even a Brahmin could subscribe to them, then it is no wonder that the Universlaist and the Unitarian churches, _which are not Christian_, originated in the Congregational Church in this country, and that even within the Congregational Church there is a large group of congregations in which even the elements of Christianity are no longer taught nor confessed.

Originally the Congregationalists were one with the Presbyterians in fighting Episcopalism in England, and with them accepted the Westminster COnfession, in 1643.  Later they broke with their allies on account of the Presbyterian church government, and, chiefly through the fanatical Robert Brown (1586), constituted themselves as Independent churches.

In 1658, the Independents of London changed the Westminster Confession in a few minor points.  (The Savoy Declaration.)  THis altered confession was accepted by the Independents of this country at a synod in Boston, in 1680.  But this acceptance they do not consider binding on anybody, not even on those who subscribe to it.

Both before and after Robert Brown took a hand in shaping the destiny of the Independents, they suffered severe persecutions in England.  But, sad to relate, when, in 1620, they landed at Plymouth Rock, Mass., none became more intolerate than they (Pilgrim Fathers).  Only their own church-members could become citizens.  Church and State were one.  Churchgoing was compulsory.  Those who disagreed with them were sorely persecuted, unmercifully banished, or condemned to death.

The Congregationalists make special effort to draw Lutherans into their fold, and are not very particular about the means which they employ toward this end.  In strong Lutheran communities they will, for instance, introduce a ceremony which closely resembles the Lutheran rite of confirmation, and some of their congregations have even adopted the Lutheran name ("Congregationalist Lutheran Church," etc.), with the sam epurpose in view.

### THE BAPTISTS
Baptists are generally not very anxious to discuss the beginning of their denomination.  They try to show at all times that Baptists, as a Church, never have persecuted other believers.  Lately, however, teachers in their higher schools have been making researches into historical archives of the Old World, and one after the other concedes that "early Baptists were called by their enemies Anabaptists."  (_Bapt. Congr._, 1911, 106.)

During great political and religious upheavals there are always some connected with the movement who commit excesses or are dissatisfied with the final settlement.  Of such there were not a few during the beginning of the Reformation.  Some, as Muenzer, Storch, and others, called "the heavenly prophets of Zwickau," found the Scriptures inadequate to their needs, and maintained that GOd had given them additional revelations.  Among the first things which they discarded was Infant Baptism.  After the death of Muenzer on the battlefield in the Peasants' War, 1524, John of Leyden gathered the prophet's followers, took possession of the city of Muenster, in Westphalia, and inaugurated a government along socialistic lines.  Not only community of goods, but also polygamy was practiced.  After the storming of the city by the neighboring princes, and execution of the chief leaders, their adherents were scattered throughout Switzerland, Germany, the Netherlands, and England, where they henceforth became known by the name Anabaptists, because, not acknowledging Infant Baptism, they rebaptized those who had been baptized as children.  Anabaptists means "those who baptize again."

The man who succeeded in creating order out of this mess is the Frieslander Menno Simmons.  Zealous, yet prudent, he succeeded in collecting the scattered members into congregations both in the Netherlands and Germany, and gave them instructions in church government and doctrine.  From that time on they became more tractable, repudiated the excesses of their fanatical ancestors, and, after the name of their leader, called themselves Mennonites.  Later they divided into numerous groups.

That the Baptists of our day do not look with pride on the historical beginning of their denomination is only human.  It is nothing to be proud of.  And yet it is a historical fact that the persecuted Anabaptists from Holland came to England, where they first made common cause with the dissenters (Independents, etc.), and only since the middle of the seventeenth centiry they have called themselves Baptists.  By this name they wish to emphasize their belief in immersion as "the only proper mode of administering Baptism," and that only to adults.  Until recently it has been generally believed that immersion was practiced among them from the very beginning.  Such is not the case however.  Up to 1641 Baptism was administered in England by sprinkling or pouring, and no other method was set forth "as the only correct way."

In church organization the Baptists agree with the Congregationalists.  There are Baptist churches, but there is no Baptist Church, except in anme; hence, no common confession.  In 1677, a "Confession of Faith" was set up in London, and again in 1688, but this is not binding on all who call themselves Baptists.  Their old belief concerning immersion as a necessary mode of Baptism is also undergoing a marked change.  Many churches hold "that the character and confession of the candidate gives sufficient validity to the ordinance, and receive baptized believers from whatever alliance they may come."  (_Bapt. Layman's Book_, p. 130.)  Hence, Baptists "are coming to have almost nothing to stand out for in separation from other denominations, except some matters of external form."  (_Bapt. Congr._, 1911, p. 91.)

Like all Reformed, the Baptists are divided into numerous sects.  "Old-School Baptists," also called "Primitive Baptists," are Calvinistic in doctrine.  Some of the others tell their own story with their name:  "Free-Will Baptists," "Anti-Mission Baptists," "Six-Principle Baptists" (Heb. 6, 1.2), "Seventh-Day Baptists," "Campbellites" (or "Disciples of Christ"), "Christians," "Weinbrennerians" ("Church of God"), "Dunkers," "River Brethren," etc., etc.

Their home missionaries are as fanatical as Muenzer, and respect no denominational lines.  The Lutherans especially are bothered by these zealots.  We can truly say of them as the Baptist professor, McGlothlin, says of the Campbellites:  "They have continued their predatory habits of proselyting down to the present time."  (_Bapt Congr._, 1911, p. 104.)  Their errors are treated in the second part of this treatise.

### THE METHODISTS
The Methodist Church is the youngest church-body among the larger Reformed denominations, dating from about 1739.  In 1729, two brothers, John and Charles Wesley, were studying at Oxford University, and, becoming troubled about the welfare of their souls, commenced to study the Bible more earnestly, and to practise the Christian virtues.  

On account of their strict methodical ways of performing these things a student, in derision, called them Methodists, a name which the Wesleys themselves shortly afterwards applied to their different "societies," since organized into independent churches.

The Wesleys did not at first intend to found a new denomination.  They only wished to inject more real Christian life and energy into the Anglican Churhc, of which they were ordained presbyters.  But very soon the "societies" which they had organized for seeking and practising holiness thought that they could no longer worship together with the rest of the church-members, and therefore organized themselves into separate congregations.  Though both John and Charles Wesley had a like share in starting the pietistic movement, yet John soon took the leading part, and is considered the real father of Methodism.

The Wesley brothers were zealous workers, it is true, but when they returned from America, in 1737, they confessed that they had labored to save others, but were not converted themselves.  This they first became, so they confessed, when John had absorbed the truths proclaimed by Luther in his introduction to the Epistle to the Romans, and Charles, through reading Luther's exposition of the Epistle to the Galatians.  

For a time the Wesleys were assisted by George Whitefield in their evangelistic efforts.  But they soon parted company, as Whitefield was a strict Calvinist in the doctrine of predestination, and became the founder of the Calvinistic Methodists, or "Huntingdon Connection."

The confession of the Methodist Church, edited by John Wesley, is only the Thirty-nine Articles of the Anglican Church slightly modified and cut down to twenty-five.  IN these we look in vain for specific Methodist doctrine and practises.  These are inferred from the writings of John Wesley mainly.  Characteristic practises and belifs of the various Methodist bodies are:  revivals (camp-meetings, protracted meetings, etc.); condemnation of every use of alcohol and tobacco; a belief that conversion, to be genuine, must be an experience of which the believer knows the exact time, and experience brought about by an immediate action of the Holy Spirit, and which is not complete unless it has been _felt_ by the Christian; a belief that man may attain perfection (perfect sanctification) in this present life; the doctrine, held in common with all Reformed sects, that Baptism and the Lord's Supper are not means of grace, but only signs of God's grace.  The Methodists wish to be styled evangelical, _par excellence_, among the Reformed Churches, but there are certainly none more legalistic than they.  The doctrine of Christian liberty is a sealed book to them.

In England the Methodist Church calls itself the Wesleyan Methodist Church, and dates its beginning from 1739, in which year John Wesley started the first congregation in Bristol, and dedicated "The Old Foundry" in London as a house of worship.  In this country the first Methodist church was started in New York, 1766, by a Wesleyan local preacher from Ireland.  Others followed and started "societies" in many places, so that in 1784 Dr. Coke, whom Wesley consecrated bishop, met sixty preachers in Baltimore for the first American conference.  This conference organized the Methodist Episcopal Church, and adopted the articles of faith edited by John Wesley.

The church government of the Methodist Episcopal Church is hierarchical to a high degree.  The congregations have very little to say.  Their ministers are appointed by the bishop, and after from two to five years are transferred to another charge by the same authority.

When the name Methodist Church is used, the official name Methodist Episcopal, is usually understood.  But the number of Methodist connections is very great.  Some insert "Methodist" in their corporate name, others omit this term.  To enumerate a few:  "The Wesleyan Methodist New Connection"; "The Primitive Methodist Connection"; "Bible Christians"; "Methodist Episcopal Church South"; "The Protestant Methodist Church"; "The Canada Wesleyan Methodist"; "African Methodist Episcopal Church"; "United Brethren"; "The Albright Methodists" (The Evangelical Association); "Jumpers"; "Howling Methodists"; and "The Salvation Army."

## Unchristian Cults
How many sects there are in this country alone no one knows, not even the Director of the Census.  Catholics would fain tell us that this state of affairs dates back only to the time of the Reformation.  There may, at the present time, be more sects than formerly, but divisions in the Church have always existed, and the Pope of Rome has not only had his hands full in pacifying and judging between warring factions of monks and their so-called "eminent teachers," but he has constantly had on hand a war of extermination against dissenters, who would not acquiesce in his teachings.  The attitude of the pope towards the Modernists of our own day is only the old story over again.  But their silence after his condemnation is the slence of the dead, -- and of the same value.

But there are sects and sects.  Some who retain the fundamental thuths of Christianity are called Christian sects, for in them there is a possibility of acquiring saving truths, -- though the danger of not finding them is also very great.  The most important of these we have discussed in the preceeding chapters.  But where even fundamentals are denied, there no salvation is possible, and such sects are at best only clubs for entertainment, if not, indeed, wholly anti-Christian and gates of hell.  Among the chief of these the following may be mentioned: --

### UNITARIANS AND UNIVERSALISTS
The late Senator Hoar of Massachusetts used to ask this conundrum, "What is the difference between Universalists and Unitarians?"  THe answer was, "The Universalists believe that God is too good to damn them, and the Unitarians believe that they are too good to be damned."  The characterization is so striking and true that little more need be said.

These churches accept the Bible as their guide in spiritual matters, but only so far as it accords with human reason.  They do not believe in the Trinity, original sin, redemption, atonement, endless punishment, etc., but believe that all will be saved, or -- some of them -- that the wicked will be annihilated.

### THE ADVENTISTS
It would not be proper to lay the heresy of the Advent Church at the door of the Baptists, and yet a Baptist clergyman is responsible for its existence.

William Miller, a licensed Baptist preacher, was neither an astronomer nor a scholarly theologian, but believed that he could foretell the day and year of the second coming of Christ.  This was in the year 1833.  People became hysterical, sold their belongings, and in "ascension robes" prepared for the event.  The Day of Judgment was set for April 14, 1844.  That day is long past, and yet the Adventists revere Miller as a great prophet.  The day has since been set time and again by other would-be prophets, but, of course, with the same results.  And yet the Adventists work with might and main to secure converts for their faith.  THe Baptists have furnished them the mode of baptizing, and the Methodists camp-meeting ideas.

The larger body among them, the Seventh-Day Adventists, denies the Holy Trinity, teaches the mortality of the soul, the final destruction of the wicked, and, especially, that Saturday must be observed as the weekly day of rest.

On account of their persistent missionary work, in which they respect no denominational lines, and their juggling with the words "Christ," "faith," "sacrifice," etc., a goodly number of simple-minded Christians are ensnared by them every year.  

Adventism is represented by a great number of sects.  Among the most active are, at present, the Russellites.  The leader of the Russellites is "Pastor" (he has never been ordained) Charles T. Russell.  The work of spreading the erroneous teaching of the "Pastor" is carried on under a confusing and misleading variety of titles, the best known of which is "The International Bible Students' Association" of Brooklyn.  Other names are:  "Watch Tower Bible and Tracts Society," formerly "Zion Watch Tower and Tract Society"; also "The Laymen's Home Missionary Movement," in the interests of which are published _Everybody's Paper_ and _the People's Pulpit_.  Most important of all the publications of "Pastor" Russell are six large volumes, entitled _Studies in Scripture_.  IN order to even mislead the blind, books and articles are prepared in raised letters, under the title of "The Gould Free Library for the Blind," South Boston, Mass.  There are also issued what are called _International Sunday-school Lessons_.  It has been proved in court that "Pastor" Russell is totally ignorant either of Greek or Hebrew, while claiming to be a great Bible interpreter; that he has been ordained by no Church or society; that he has been divorced by his wife; that he is connected with various business corporations, all of which are under his absolute control, and which hold stock valued at millions of dollars.  We append a brief summary of the false teachings assiduously being spread by Russell and his followers, the Millennial Dawn religion.

1.  Russellism denies the doctrine of the Trinity.

2.  It denies that Jesus Christ was God before His incarnation.

3.  It teaches that Christ was only a created spirit.

4.  In incarnation He ceased to be a spirit, and became the second Adam.

5.  As the second Adam He had only one nature.

6.  His nature of humanity was annihilated on the cross.

7.  He did not rise in the body in which he died.  

8.  The body in which He died may have been dissolved into gas.  

9.  The body in which He appeared after death was nothing more than a momentarily materialized appearance, which was finally dissolved

10.  Jesus Christ is not now a man.

11.  The "Man Christ Jesus" no longer exists.

12.  Jesus Christ is now an invisible spirit-being.

13.  He came to the world in 1874 as an invisible spirit-being.

14.  The millennium will begin in 1914.  (!)

15.  All the dead out of Christ will be raised at that time.

16.  All the unrighteous and wicked dead will be raised and made perfect and innocent like Adam before the Fall.

17.  All the unrighteous and wicked dead will be given a second chance.

18.  The more wicked they have been in this life, the more likely they will be, through the "experience" of sin, to accept the Gospel of the second chance.  

19.  Those who accept the second chance will have everlasting life.

20.  Those who get everlasting life will sustain it by eating food.

21.  Those who do not want to live forever will have the privilege of being asphyxiated in the lake of fire.

22.  The assurance given to the wicked and sinful is that there is no suffering for sin.

23.  Those who do not care for heaven need not be afraid of hell.

24.  The finally impenitent are extinguished here, and annihilated.

### QUAKERS
"Quiet as a Quaker meeting" is a byword.  The reason for this is that George Fox, the founder of the sect, discarded the Bible as an insufficient message from God, and sought consolation in "inner promptings, whisperings, and moving of the spirits."  In their so-called services no Bible-text is expounded, but "when the Spirit moves" a man or woman, that person speaks; but until then there is silence.  And when, after waiting a reasonable time, no one is "moved," the congregation goes home.

Quakers also wish to be known as the "Society of Friends."  They hate ostentation, never remove the hat in saluting any one, and call everybody "thou."  They will neither take an oath nor serve in the army.

The theology of the Quakers may be somewhat more definite now than at the time of their founder, but not sufficiently so as to characterize them as Christians.  Their founder's everlasting refrain ran like this:  "Not Scripture, but Spirit!  Not Christ for us, but in us!  Not churches ('tower buildings') and bells, not Sacraments and dogmas, but only the inner light which GOd ignites in the conscience of every one, and through which the SPirit of Christ regenerates and comforts man."  This sounds plausible, but as long as they deny the atonement, Christ will not send the regerating Spirit.  But without regeneration no one shall see God.  (John 3, 3.)  The Quakers are not the only ones relying on the "Spirit" and the "inner light."  But they seem to rely on a "Spirit" and "Light" which is not always to be relied on.  Thus we find them divided into "orthodox," "dry," "wet," "Hicksite," "fighting," "progressive," "primitive," "Baptist," "Christian," and "Keithian" Quakers.  

Quakerism is only a type of a large class of cults, both ancient and modern, the adherents of which, like the rich man (Luke 16, 27), find, as they think, the Bible insufficient to the needs of mankind.  But whatever their achievements may be in our eyes, the Holy Spirit says of them that "other foundation can no man lay than that is laid, which is Jesus Christ."  (1 Cor. 3, 11.)

### THE MORMONS
This old world of ours has seen many queer and brazen humbugs, but not till Mary Baker-Eddy proclaimed Christian Science has anything appeared quite equal to Mormonism, or, as its adherents wish to be known, The Church of Jesus Christ of Latter-Day Saints, founded by Joseph Smith.

ne Solomon Spaulding (died 1818) amused himself, after retiring from the ministry, by writing a book, in Biblical style, purporting to be the history of the peopling of of America by the ten lost tribes of Israel.

This manuscript Joseph Smith secured, and, after altering a little here and there (without, however, improving its style, for he was very poorly educated) he published it in 1830 under the name of _The Book of Mormon_, and proclaimed it to be of equal authority with the Bible.

But the real author's name does not appear on its pages.  Instead, it purports to be a revelation.  An angel, so he said, pointed out to Joseph Smith that "on the west side of a hill, not far from the top, about four miles from Palmyra, N.Y., near the road to Manchester," he would find plates of gold inscribed with hieroglyphs in "reformed Egyptian," and a pair of eye-glasses called "Urim and Thummim."  And Joseph found them, so he says, and by sitting behind a curtain, dictating to a confederate on the other side, he gave to a benighted world the greatest light in its history:  _The Book of Mormon_.  What became of the plates is still a mystey.  Forsooth, certain persons bear witness, on a front page in the book, that they have seen them, but it is only the testimony of ill-reputed people in favor of one of the same kind.

The plates are said to have been hidden in the hill about A. D. 420.  Yet the inscriptions mention Calvinism, Universalism, Methodism, Millenarianism, and Roman Catholicism!  

Though polygamy is one of the main tenets of Mormonism, still it is condemned in _The Book of Mormon_.  It was an after-thought, and was revealed to the churhc later!

To those who calmly compare Mormonism with Christianity there is not much danger.  But those who listen only to the glib-tongued "missionaries," who conceal more than they divulge, Mormonism is as alluring a scheme as the devil has yet concocted.  Mormonism is by its missionaries pictured as a paradise on earth; hence the rule of the ignorant and the sensual to Salt Lake City and other Mormon centers.  

### CHRISTIAN SCIENCE


