# PART II.  Doctrines of the Church {.unnumbered}

## Concerning the Truth\index{Christian Religion, Truth of} of the Christian Religion
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

Of the many religions in the world, ancient as well as modern, the religion of the Bible is the only true one.

Acts 17, 29. 30:  "Forasmuch, then, as we are the offspring of God, we ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man's device.  And the times of this ignorance God winked at, but now commandeth all men everywhere to repent."

John 17, 3:  "And this is life eternal, that they might know Thee the only true God, and Jesus Christ, whom Thou hast sent."  (John 3, 18; 1 Cor. 8, 4; Ex. 20, 3-6.)

\begin{center}
\textsl{Testimony:--}
\end{center}

"Whosoever will be saved, before all things it is necessary that he hold the true Christian faith.  Which faith except every one do keep whole and undefiled, without doubt he shall perish everlastingly." -- _Athanasian Creed_.

\begin{center}
\textsc{Error.}
\end{center}

1.  Carnal mind is in enmity against God.  (Rom. 8, 7.)  Hence man's unwillingness to be governed by Him.  He tries to forgetHim, deny Him; but all to no purpose,-- except, perhaps, for a time.  But the devil is always trying some method whereby he may rob man of the Word of God, so that he shall not believe and be saved.  (Luke 8, 12.)  And one way of accomplishing this is to make him believe that one religion is as good as another, or that Christians "will not be alone about inheriting heaven."

The Swiss reformer Zwingli believed "that all the ancient noble heathens who walked uprightly according to the light they had were also saved."  (_Expos_. _Fidei_, II, 559.)

The Quaker Barclay, in his _Apology_ (10, 2), voices the same thought as regards heathen, Turks, and Jews at the present time.

\begin{center}
\textsl{But God says:--}
\end{center}

Acts 4, 12:  "Neither is there salvation in any other; for there is none other name under heaven given among men whereby we must be saved."  (See Gospel of St. John.)

1 Cor. 1, 21:  "For after that, in the wisdom of God, the world by wisdom knew not God, it pleased God by the foolishness of preaching to save them that believe."  (2 Thess. 1, 7-10:  "punishment for all who do not know and obey the Gospel of our Lord Jesus Christ.")

2 Thess. 2, 10-12:  "Because they received not the love of the truth that they might be saved, ... God shall send them strong delusions that they should believe a lie, that they all might be damned who believed not the truth."

John 14, 6:  "I am the Way, the Truth, and the Life; no man cometh unto the Father but by Me."

Christ warned against being an "unbeliever, a heathen and a publican."  (Matt. 18, 17; Mark 16, 17.)

2.  A large class of unbelievers call themselves agnostics\index{Agnostics}.  This sounds better than atheists and freethinkers, but they are in reality their triplet brother.  The "believ" of the agnostic is "We do not know whether there is a God."  ("The problem of existence has not been solved, and it is insoluble":  (Thomas Huxley.)  This dictum has been applied, not only to human existence, but to God Himself, as well as to His revelation.

\begin{center}
\textsl{But God says:--}
\end{center}

John 1, 14:  "And the Word was made flesh, and dwelt among us; and we beheld His glory, the glory as of the Only-begotten of the Father, full of grace and truth."

1 John 1, 1. 3:  "That which was from the beginning, which we have seen which we have heard, ... declare we unto you."

2 Pet. 1, 16:  "For we have not followed cunningly devised fables when we made known unto you the power and coming of our Lord Jesus Christ, but we were eye-witnesses of His majesty."  (See vv. 17. 18.)

Rom. 1, 19:  "even the heathen acknowledge the existence of God.

_What Is an Atheist?\index{Atheists}_ -- A snare to the simple-minded Christian is the oft repeated assertion that so and so was no atheist, because he had confessed his belief in a personal God or, perhaps, in "a Higher Power."  It is true, the words of the Psalmist (14, 1), "The fool saith in his heart, There is no God," describe more nearly the person called "atheist."  But all who do not confess the true God are properly to be classed as having no God at all.  Christ says:  "He that honoreth not the Son honoreth not the Father."  (John 5, 23.)  "Whosoever shall deny Me before men, him will I also deny before My Father which is in heaven."  (Matt. 10, 33.)  And the Holy Spirit testifies:  "Whosoever denieth the Son, the same hath not the Father."  (1 John 2, 23.  Compare also 2 John, v. 9.)

_Lodge Religion_. -- Under this head must be ranged all lodges which require a "belief in a Supreme Being" from their members, but who do not define this "Being" as the Triune God, Father, Son, and Holy Ghost, and studiously avoid using the name of Jesus in their so-called prayers.  Silently (and here intentionally) to omit a confession of the Savior is to deny Him, and be classed as heathen.  (Matt. 18, 17.)  And Christ explicitly teaches that He is the Way, the Life, and the Truth, and that no man cometh unto the Father but by Him.  (John 14, 6.)

_Evolution_. -- The notion is also prevalent that Christianity, revealed religion, "is subject to the laws of evolution."  Aside from the fact that "the laws of evolution" are only imaginings of depraved human nature, which fain would escape just punishment at the hands of God, "progressive Christianity" is simply an absurdity.  What of a Christianity in which the life, teachings, and deeds of a Christ Jesus, little by little, should be superseded by -- what?  Can you think of a moral law which could supersede the Ten Commandments?  Of a just God more righteous than Jehovah?  more loving than Jesus?  more merciful than He who sent His only-begotten Son as the Savior for the whole world?  more merciful than He who embraces the Prodigal (Luke 15, 20), pardons the adulteress (John 8, 11), promises heaven to the thief on the cross (Luke 29, 43), and prayed even for His enemies?

No doubt, it is considered the height of wisdom at the present time to assert that "the law of evolution" also underlies the Christian religion. But what does history tell us concerning those who have come under its spell?  Heathenism is nothing but the result of a trial to improve on the revelation and government of God.  The Babylonian captivity of the Jews and the final dispersement of them over all the earth is the outcome of a similar experiment.  The early Christian Churches in Asia and elsewhere tried their hands at the same thing, and were rewarded by -- Mohammedanism.  And what is popery, Jesuitism, rationalism but the outcome of efforts to apply "the law of evolution" to religion!  Evolution, indeed, but _always_ an evolution downward.

Though the theory on which Darwinian evolution rests has been discarded as insufficient by conscientious scientists, yet the reechoing of it is still heard in some of our higher institutions of learning, not to mention our normal schools, where our common-school teachers are trained.  Hence we often read of this or that "professor," in our daily papers, who adjudges the remains of some prehistoric (?) animal as being so or so many millions of years old.  These opinions finally find their way into text-books and are henceforth promulgated as "gospel truths."  But what reliance may be put upon them the following well-supported facts will show.

1.  The Neanderthal Skull, has, since 1856, been offered as one of the chief proofs for the evolution of man from a lower animal, and has been considered about 300,000 years old.  Dr. Meyer, of Bonn, proved that it is the skull of a Russian Cossack killed in 1814.  

2.  The Calaveras Skull, in the California State Museum, was placed in a mine-shaft, 150 feet deep, as a practical joke.

3.  The "Colorado Specimen" was pronounced by a Columbia College "scientist" to be "the missing link," one million and a half years old.  Cowboys since proved the bones to be that of a pet monkey which they had buried there.

4.  The Croatian Skeletons (Austria) are the bones of degenerate human beings, -- nothing more.

5.  The Pithecanthropus Erectur has for some years (since 1891) been the most popular relic with evolutionists.  The collection consisted of a skull above the eyes, a leg-bone, and two teeth, -- found in Java at separate places.  The age of this "missing link" was guessed by various scientists to be from one hundred thousand to one million years!  According to measurements the skull is that of an idiot.  (See _The Other Side of Evolution_, Alex. Patterson, D. D. Winona Publ. Co., Chicago, 1903.)

## The Holy Scriptures
\begin{center}
\textbf{A.  The Bible Is God's Revelation to Mankind}

\textsc{Bible Doctrine.}
\end{center}

The Bible, comprising the canonical books of the Old and the New Testament, is God's unerring and only revelation to mankind.

Luke 16, 29:  "They have Moses and the prophets; let them hear them."

1 Thess. 2, 13:  "When ye received the Word of God which ye heard of us, ye received it not as the word of men, but, _as it is in truth_, the Word of God."

John 17, 17:  "Sanctify them through Thy truth; Thy Word is truth."

\begin{center}
\textsl{Lutheran Testimony}
\end{center}

"We believe, teach, and confess that the only rule and standard according to which at once all dogmas and teachers should be esteemed and jusged are nothing else than the prophetic and apostolic Scriptures of the Old and the New Testament, as it is written:  'Thy Word is a lamp unto my feet and a light unto my path' (Ps. 119, 105), and St. Paul:  'Though an angel from heaven preach any other gospel unto you, let him be accursed' (Gal. 1, 8). (_Form. Con._, Epit., Introd., § 1.)

\begin{center}
\textsc{Error.}
\end{center}

1.  The evolutionists one and all discredit the narrative in Genesis, first chapter, concerning creation.  Of the Bible, as revelation, Haeckel says:  "It is the invention of man's imagination.  The so-called truth which believers find in it is a human speculation, and the 'childlike' faith in this irrational revelation is only superstition."  (_The Riddle of the Universe_, 123.)

\begin{center}
\textsl{But God says:--}
\end{center}

Rom. 3, 1. 2:  "What advantage, then hat the Jew?  Much every way:  chiefly, because that unto them were commiteed _the oracles of God_."

Heb. 1, 1. 2:  "God, who at sundry times and in diverse manners spake in time past unto the fathers by the prophets, _hath in these last days spoken unto us_ by His Son."

1 Pet. 1, 16:  "For we have _not followed cunningly devised fables_ when we made known unto you the power and coming of our Lord Jesus Christ, but were eye-witnesses of His majesty."

2.  The so-called higher critics\index{Critics, Higher} fain would find all kinds of flaws and faults in the Bible:  Creation is a myth; the patriarchs never lived, at least not at the time states; Moses, and most of the other authors, never wrote the books ascribed to them; the contents are unreliable; the so-called prophecies are post-event descriptions, etc., etc.

\begin{center}
\textsl{But God says:--}
\end{center}

1 Tim. 4, 1:  "Now _the Spirit speaketh_ expressly that in the latter times some shall depart from the faith, giving heed to _seducing spirits_ and doctrines of devils."

John 1, 1-3:  "In the beginning was the Word, and the Word was with God, and the Word was God.  All things were made by Him, and without Him was not anything made that was made."

Luke 20, 37. 38:  "The Lord is the God of Abraham and the God of Isaac and the God of Jacob; for He is not a God of the dead, but of the living."

Luke 24, 27:  "And _beginning at Moses_ and all the prophets, He expounded unto them in all the Scriptures the things concerning Himself."

John 6, 63:  "The words that I speak unto you, they are spirit, and they are life."

Matt. 24, 35:  "Heaven and earth shall pass away, but My words shall not pass away."

John 12, 48:  "He that rejecteth Me, and receiveth not My words, hath one that judgeth him; the word that I have spoken, the same shall judge him in the last day."

John 10, 35:  "The Scripture cannot be broken."

\textsc{The Apocryphal Books.} -- Some editions of the Bible contain a number of books called Apocrypha\index{Apocryphal Books} (hidden).  The name implies that the authors are unknown, and their writings of doubtful value.

The Apocrypha of the Old Testament comprise some fourteen books and those of the New Testament about twenty-five.  The latter have never appeared in any Protestant Bible.

In 1546, the Catholic Church\index{Catholic Church!zzzzz@\igobble|seealso{Roman Catholic Church}} decreed, through the Council of Trent, that the old Testament apocryphal books were to be included among the canonical (rule-giving) books of the Bible.  This was done in order to gain certain proof-texts for the doctrines of purgatory, prayers for the dead, and for strengthening the position of the pope generally.  However, no council can decree what shall, or shall not, be the Word of God.  The canonicity of the Bible is deduced from a multitude of proofs peculiarly its own.  The following, among many, may suffice here.  1) The declaration of the different writers that God has spoken through them.  2) The loftiness and sublimity of the Bible-text in comparison with that of secular books.  3) The united testimony of the Church concerning both the Old and the New Testament.  4) The repeated references of Christ and the apostles to numberless statements in the canonical books, but silence as to the apocryphal.  5) The sufficiency of the canonical Scriptures as declared by Christ Himself.  (Luke 16, 31; John 5, 39; 10, 35.)

\begin{center}
\textbf{B.  The Bible is Given by Inspiration of God.}

\textsc{Bible Doctrine.}
\end{center}

The contents of the Bible were revealed to the sacred writers by inspiration of the Holy Spirit

2 Tim. 3, 16:  "All Scripture is given _by inspiration of God_, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness."

2 Pet. 1, 21:  "For the prophecy came not in old time by the will of man, but holy men of God _spake as they were moved by the Holy Ghost_."

\begin{center}
\textsl{Testimony of the Creed:--}
\end{center}

"And I believe in the Holy Ghost, the Lord and Giver of life; ... who spake by the prophets." -- _Nicene Creed_, § 7.

\begin{center}
\textsc{Error.}
\end{center}

The great majority of modern exegetes, especially the so-called higher critics, maintain that "science" forbids the acceptance of an inspiration different from that of a Shakespeare or a Milton.  And even if the different authors were under the influence of a higher power, they were children of their times, and hence their opinions were biased, and they were subject to errors in judgment, etc.

\begin{center}
\textsl{But God says:--}
\end{center}

1 Cor. 2, 12. 13:  "NOw we have received, not the spirit of the world, but the Spirit which is of God, that we might known the things that are freely given to us by God.  Which things also we speak, not in the _words_ which man's wisdom teacheth, but _which the Holy Ghost teacheth_, comparing spiritual things with spiritual."

1 Cor. 2, 7. 10:  "But we speak the wisdom of God in a mystery, even the hidden wisdom, which God ordained before the world unto our glory; which none of the princes of this world knew.  But _God hath revealed them unto us_ by His Spirit."

Matt. 10, 20:  "For it is not ye that speak, but the Spirit of your Father which speaketh in you."  (2 Sam. 23, 2. 3.)

1 Cor. 1, 23:  "But we preach Christ crucified, unto the Jews a stumbling-block and unto the Greeks foolishness."

Gal. 1, 20:  "Now the things which I write unto you, behold before God, I lie not."  (1, 8. 9.)

\textsc{Note.} -- A great many theologians at the present time have given up the belief in verbal inspiration, and contend that God only gave the authors an "impulse" to write, and what to write about, or, at best, that the "concept," or "idea," was inspired.  But this, together with the assertion that the different authors have been mistaken in several things, is simply destroying the foundation of all faith and hope.  If God has not told us in explicit words what His will is, the hope of the Christian is no better than that of a Rationalist.

But a few passages from Scripture will show how the Bible stands on the question.

Ex. 4, 12:  "Now, therefore, go, and I will be with thy mouth, and teach thee what thou shalt speak."

Ex. 34, 27:  "And the Lord said unto Moses, Write thou these words; for after the tenor of these words I have made a covenant with thee and with Israel."

2 Sam. 23, 2:  "The Spirit of God spake by me, and His Word was upon my tongue."  (Of this Christ says in Mark 12, 36:  "David himself said _by the Holy Ghost_.")

Acts 2, 4:  "And they were filled with the Holy Spirit, and began to speak with other tongues as the Spirit gave them utterance."

Mark 13, 11:  "For it is not ye that speak, but the Holy Ghost."

In almost innumerable places we read:  "Thus saith the Lord"; "The Lord said"' "The word of the Lord," and the like, especially numerous in the writings of the prophets.  So also the message of the apostles:--

1 Cor. 2, 13:  "Which things also we speak, not in words which man's wisdom teacheth, but which the Holy Ghost teacheth."

1 Thess. 2, 13:  "When ye received the Word of God which ye heard of us, ye accepted it not as the word of men, but, as it is in truth, the Word of God."

\begin{center}
\textbf{C.  The Interpretation of the Bible.}

\textsc{Bible Doctrine.}
\end{center}

The meaning of the words of Scripture must be sought in the Scriptures themselves, not outside of them.

2 Pet. 4, 11:  "If any man speak, let him speak as the oracles of God."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}
"We have, however, another rule, _viz_.:  That the Word of God should frame articles of faith; otherwise no one, not even an angel." -- _Smalcald Articles_, II, 2, 15.

\begin{center}
\textsc{Error.}
\end{center}

Zwingli and Calvin\index{Calvin} both declared that human reason must be the judge of Holy Scripture.  Zwingli gives this counsel:  "Philosophical argumentation through conclusions of reasoning must not be neglected." -- _Expos. Chr. Faith_.

Calvin says:  "Can you prove through reasoning that this contains nothing unreasonable?  Yes, if it be conceded that the Lord has instituted nothing that is contrary to reason." -- _Geneva Catechism_.

This is the fundamental error of all sects, ancient and modern.  And the Reformed Churches, one and all, carry the image of their originators.

\begin{center}
\textsl{But God says:--}
\end{center}

Is. 8, 20:  "To the Law and to the testimony:  if they speak not according to this Word, it is because there is no light in them."

2 Cor. 10, 5:  "We bring into captivity every thought to the obedience of Christ."

1 Cor. 2, 14:  "But the natural man receiveth not the things of the Spirit of God; for they are foolishness unto him; neither can he know them, because they are spiritually discerned."

Rom. 9, 20:  "O man, who art thou that repliest against God?"

\textsc{Note.} -- Under the topic "Means of Grace" the doctrine of Holy Scripture will be further discussed.

## Original Sin
\begin{center}
\textsc{Bible Doctrine and Lutheran Testimony}
\end{center}

"All men, after Adam's fall, begotten after the common course of nature, are born with sin, that is, without the fear of God, without trusting Him, and with fleshly appetites; at that, this disease, or original fault, is truly sin, condemning and bringing eternal death now also upon all that are not born again by the Holy Spirit." -- _Augsb. Conf._, Art. II.)

Gen. 8, 21:  "The imagination of man's heart is evil from his youth."  (6, 5.)

Eph. 2, 1:  "Ye were dead in trespasses and sin."

Rom. 3, 22. 23:  "There is no difference; for all have sinned, and come short of the glory of God."

Eph. 2, 3:  "We were by nature the children of wrath."

Ps. 51, 5:  "I was shapen in iniquity, and in sin did my mother conceive me."

Rom. 5, 12:  "By one man sin entered into the world, and death by sin; and so death passed upon all men, for that all have sinned."

\begin{center}
\textsc{Error.}
\end{center}

The Reformed Churches do not express themselves with sufficient exactness in their definition of Original Sin.  The _Methodists_, for instance, say in their _Articles of Religion_:  "Man is very far gone from original righteousness."  (Art. 7.)  To this a Methodist writer makes the remark that "how far is not stated.  Obviously the meaning is that the image of God is not wholly destroyed."  The practise in the Methodist Church corroborates this assertion.  The doctrine of Original Sin is now very rarely taught from Reformed pulpits, and has all but disappeared from the sectarian press.

\begin{center}
\textsl{But God says:--}
\end{center}

Rom. 7, 18:  "For I know that in me, that is, in my flesh, dwelleth no good thing."

Rom. 8, 7:  "The carnal mind is enmity against God; for it is not subject to the Law of God, neither, indeed, can be."  (1 Cor. 2, 14; John 3, 6.)

Ps. 53, 3:  "The wicked are estranged from before birth; they go astray as soon as they be born, speaking lies."  (Is. 48, 8.)

## Redemption
\begin{center}
\textbf{A.  Redemption Is Through Christ.}

\textsc{Bible Doctrine.}
\end{center}

Gal. 3, 13:  "Christ has redeemed us from the curse of the Law, being made a curse for us."  

Matt. 5, 17:  "Think not that I am come to destroy the Law or the prophets; I am not come to destroy, but to fulfill."  (3, 15.)

Rom. 8, 3. 4:  "For what the Law could not do, in that it was weak through the flesh, God, sending His own Son in the likeness of sinful flesh, and for sin, condemned sin in the flesh, that the righteousness of the Law might be fulfilled in us, who walk not after the flesh, but after the Spirit."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"For since Christ is not alone man, but God and man in one undivided Person, He was as little subject to the Law, because He is the Lord of the Law, as, in His own Person, to suffering and death.  Therefore His obedience, not only in suffering and dying, but also that He in our stead was voluntarily subject to the Law, and fulfilled it by His obedience, is imputed to us for righteousness, so that, on account of this complete obedience, which by deed and by suffering, and in life and in death, He rendered His heavenly Father for us, God forgives our sins, regards us godly and righteous, and eternally saves us." -- _Form. Conc._, III, § 15.

\begin{center}
\textsc{Error.}
\end{center}

The _Moravians_ (Brethren\index{Brethren}) and _Methodists_ speak in their catechisms, under this head, of Christ, only as a _type_, or _example_.  "How is the life of Christ on earth to be considered?  His life on earth was perfectly holy, and is therefore an example for us to follow."  (_Mor. Cat._, Qu. 48.) -- "What does the life of Christ represent?  A prototype of perfect goodness and holiness." -- _Meth. Cat._, No. 3, p. 23.

\textsc{Note.--} Present-day Christianity, among the sects and enthusiasts, is all of this variety.  "Be good," "Follow in His steps," are slogans heard on every hand.  Forsooth, true Christians also strive to be good, and to follow in the footprints of the Savior.  But these things do not _make_, but only _adorn_ a Christian.  We are saved, not by following "in His steps," but by accepting His redemption.

\begin{center}
\textsl{But God says:--}
\end{center}

Gal. 4, 4. 5:  "But when the fulness of the time was come, God sent forth His Son, amde of a woman, made under the Law, to redeem them that were under the Law, that we might receive the adoption of sons."

Rom. 10, 4:  "For Christ is the end of the Law for righteousness to every one that believeth."  (Phil. 2, 7. 8)

\begin{center}
\textbf{B.  Redemption Is Universal}

\textsc{Bible Doctrine.}
\end{center}
Christ has through His suffering and death redeemed the whole world.

Rom. 5, 19:  "For as by one man's disobedience many were made sinners, so by the obedience of One shall _many_ be made righteous."

John 1, 29:  "Behold the Lamb of God, which taketh away the sins of the _world_."  (3, 16; 12, 47.)

Gen. 22, 18:  "In thy seed shall _all nations of the earth_ be blessed."

Luke 2, 10:  "I bring you good tidings of great joy, which shall be to _all people_."

2 Pet. 3, 9:  "The Lord is not willing that any should perish, but that all should come to repentance."  (Rom. 11, 32.)

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"The first and chief articles is this, that Jesus Christ, our God and Lord, died for our sins, and was raised again for our justification.  Rom. 4, 25.  And He alone is the Lamb of God, which taketh away the sins of the world (John 1, 29); and God has laid upon Him the iniquities of us all.  Is. 53, 6."  -- _Smalc. Art._, II, 1. 2.

\begin{center}
\textsc{Error.}
\end{center}

_Presbyterians, Congregationalists\index{Congregationalists}_, and _Calvinistic Baptists\index{Baptists}_ state in their confessions that Christ has redeemed the elect _only_.  In the _Westminster Confession_ we read:  "As God hath appointed the elect unto glory, He, by the eternal and most free purpose of His will, foreordained all the means thereunto.... _Neither are any other redeemed by Christ, effectually called_, justified adopted, sanctified, and saved, but the elect only." -- (III, § 6.)  And again:  "The Lord Jesus, by His perfect obedience and sacrifice of Himself, ... hath fully satisfied the justice of His Father, and purchased not only reconciliation, but an everlasting inheritance in the kingdom of heaven, _for all those whom the Father hath given unto Him_" (_i. e._, for the elect _only_).--_Westm. Conf._, VIII, 5.  (See also _Savoy Declaration_ and _Bapt. Conf_. of 1688.)

\begin{center}
\textsl{But God says:--}
\end{center}

2 Cor. 5, 15:  "He died _for all_, that they which live should not henceforth live unto themselves, but unto Him which died for them and rose again."

Matt. 18, 11:  "The Son of Man is come to save _that which was lost_."

1 Tim. 4, 10:  "We trust in the living God, who is the Savior of _all men_, specially of those that believe."

1 John 2, 1. 2:  "If any man sin, we have an Advocate with the Father, Jesus Christ the Righteous; and He is the propitiation for our sins, and not for ours only, but also for the sins of the _whole world_."  (rom. 5, 10; Is. 53.)

2 Pet. 2, 1:  "Denying the Lord that brought them, and bring upon themselves swift destruction."  (Christ died also for those who by reason of their unbelief are finally lost.)

## Conversion\index{Conversion}
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

"Conversion is not an effect of man's own power and strength, but an act and gift of the Holy Spirit." -- _Chemnitz's Enchiridion_.

Acts 11, 18:  "God hath also to the Gentiles granted repentance unto life."

Phil. 2, 13:  "For it is God which worketh in you both to will and to do of His good pleasure."

Heb. 13, 20. 21:  "Now the God of peace ... make you perfect in every good work to do His will, working in you that which is well-pleasing in His sight."

John 15, 5:  "Without Me ye can do nothing."

2 Cor. 3, 5:  "Not that we are sufficient in ourselves to think anything, as of ourselves, but our sufficiency is of God."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"In spiritual and divine things the intellect, heart, and will of the unregenerate man cannot, in any way, by their own natural power, understand, believe, accept, think, will, begin, effect, do, work, or concur in working anything, but they are entirely dead to good and corrupt; so that in man's nature, since the fall, there is, before regeneration, not the least spark of spiritual power remaining still present, by which, of himself, he can prepare himself for God's grace, or accept the offered grace, or, for and of himself, be capable of it, or apply or accommodate himself thereto, or, by his own powers, be able of himself, as of himself, to aid, do, work, or concur in working anything for his conversion, either entirely, or in half, or in even the least or most inconsiderable part, but he is the servant and slave of sin (John 8, 34; Eph. 2, 2; 2 Tim. 2, 26).  Hence the natural free will, according to its perverted disposition and nature, is strong and active only with respect to what is displeasing and contrary to God." -- _Form. Conc._, Art. II, § 7.

\begin{center}
\textsc{Error.}
\end{center}

The so-called _Free-will Baptists_ tell by their very name what they teach about conversion.  But not so the _Methodists_.  In section 8 of their _Articles of Religion_ they seem to disclaim the concurrence of the Holy Spirit, but their chief teachers are self-confessed _Synergists_, and their whole evangelistic and revivalistic work is based on the old heretical belief in freedom of the will.  John Wesley says in his _Scripture Doctrine of Predestination_:  "Oh, you are a defender of the freedom of the will, you assume a free will in man!  I assume nothing but what Scripture says, and that you ought to allow me to assume.  I do not assume that a man has will or power to do anything good of himself, but by the grace of God we may do everything.  We believe that the moment Adam fell, he had no more freedom of the will, but that when God, in His free grace, promised him and his seed a Savior, He then _returned_ to humanity a free will and power to accept the proffered salvation."  Professor W. F. Warner, in his _Systematic Theology_, speaks in similar terms.  Also T. N. Ralston, in his _Outlines of Theology_.  _The Cumberland Presbyterians_ also err here.  In their _Origin and Doctrine_ we read:  "We object to the idea that man is passive in matters pertaining to salvation until God revives and renews him."  (p. 86.)

\begin{center}
\textsl{But God says:--}
\end{center}

Jas. 1, 18:  "_Of His own will_ begot He us with the Word of Truth, that we should be a kind of first-fruits of His creatures."

1 Cor. 12, 3:  "No man can say that Jesus is the Lord _but by the Holy Ghost_."

Jer. 13, 23:  "Can the Ethiopian change his skin, or the leopard his spots?  Then may ye also do good that are accustomed to do evil."

Matt. 7, 16:  "Do men gather grapes of thorns or figs of thistles?"  (12, 34.)

\textsc{Free Will.--} We often hear this expression:  "We have a free will, and can do as we please."  To this the _Augsburg Confession_ makes this reply:  "Concerning free will they teach that man's will has some liberty to work a civil righteousness, and to choose between things that are subject to human reason, but that it has no power to work the righteousness of God, or a spiritual righteousness, without the Spirit of God, because that the natural man receives not the things of the Spirit of God, 1 Cor. 2, 14.  But this is wrought in the heart when man receives the Spirit of God through the Word." -- Art XVIII.

## Predestination
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

a.  God has shown mercy to all mankind, and wishes all to be saved.

1 Tim. 2, 4:  "God will have all men to be saved, and to come unto the knowledge of the truth."

2 Pet. 3, 9:  "The Lord is not willing that any should perish, but that all should come to repentance."

Ezek. 33, 11:  "As I live, saith the Lord God, I have no pleasure in the death of the wicked, but that the wicked turn from his way and live."  (18, 33; John 3, 16.)

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Therefore, if we wish with profit to consider our eternal election to salvation, we must ine very way hold rigidly and firmly to this, _viz_., that, as the preaching of repentance, so also the promise of the Gospel is universal, _i. e._, it pertains to all men (Luke 24, 47).  Therefore Christ has commanded 'that repentance and remission of sins should be preached in His name among all nations.'  For God so loved the world, and gave His Son (John 3, 16).  Christ bore the sins of the world (John 1, 29), gave His flesh for the life of the world (John 6, 51); His blood is the propitiation for the sins of the whole world (1 John 1, 7; 2, 2)," etc. -- _Form. Conc._, Art. XI, 28.

\begin{center}
\textsc{Error.}
\end{center}

To be a _Calvinsit_ is to believe what has been properly called the "monstrous doctrine" that God does _not_ desire the salvation of _all_ mankind.  IN his _Institutes_ Calvin\index{Calvin} declares that "by predestination we mean the eternal decree of God, by which He determined with Himself whatever He wished to happen with regard to every man.  All are not created on equal terms, but some are preordained to eternal life, _others to eternal damnation_; and, accordingly, as each has been created for one or other of these ends, we say that he has been predestined to life _or death_."  (III, 21, 5.)  "He arranges all things by His sovereign counsel, in such a way that individuals are born who are doomed from their inception to certain death, and are to glorify Him by their destruction."  (III, 23, 6.)

\begin{center}
\textsl{But God says:--}
\end{center}

Rom. 11, 32:  "God hath concluded them _all_ in unbelief, that He might have mercy _upon all_."

1 John 2, 2:  "And He is the propitiation for our sins, and not for ours only, but also for the sins of the _whole world_."

Matt. 23, 37:  "O Jerusalem, Jerusalem, ... how often would I have gathered thy children together, even as a hen gathereth her chickens under her wings, and _ye would not_."

\begin{center}
\textsc{Bible Doctrine.}
\end{center}

b.  In choosing His elect, God did not proceed in an arbitrary absolute manner, but chose them in Christ Jesus.

Eph. 1, 3-6:  "Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spriitual blessings in heavenly places in Christ; according as He hath chosen us _in Him_ before the foundation of the world, that we should be holy and without blame before Him in love; having predestinated us unto the adoption of children by Jesus Christ to Himself, according to the good pleasure of His will, to the praise of the glory of His grace, wherein He hath _made us accepted in the Beloved_."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Therefore this eternal election of God is to be considered in Christ, and not beyond or without Christ.  For 'in Christ,' testifies the Apostle Paul (Eph. 1, 4 sq.), 'He hath chosen us before the foundation of the world,' as it is written:  'He hath made us accepted in the Beloved.'" -- _Form. Conc._, XI, § 65 (5. 9).

\begin{center}
\textsc{Error.}
\end{center}

1. The fountainhead of modern error concerning this doctrine is _John Calvin\index{Calvin}_.  To him predestination was the central doctrine of the Christian religion.  And more, -- predestination he considers strictly an arbitrary act of God.  "I repeat," he says, "that we must ever return to the mere pleasure of the divine will." -- _Iinst._, III, 23, 4.

2. The _Reformed Church_, specially so called, expresses its belief thus:  "If we are not to be ashamed of the Gospel, we must confess what it clearly teaches, that God, according to His eternal pleasure and moved by no other cause, has ordained some unto salvation, whereas others were rejected." -- _Cons. Genev._, 224.

3. _Congregationalists\index{Congregationalists}_ and _Baptists\index{Baptists}_, in their respective confessions, agree with the _Presbyterians_ when the latter say:  "By the decree of God, for the manifestation of His glory, some men and angels are predestined unto everlasting life, and others foreordained to everlasting death." -- _Westm. Conf._, III, 3, 7.

\textsc{Note.} -- In 1887 and 1903, the Presbyterian Church (North) added two chapters to their confession (34, 35) and also appended a _Declaratory Statement_ concerning predestination.  According to this "Statement," Chapter III is to be understood as _not_ teaching foreordination to death; and Chapter X, 3, that no children dying in infancy are lost.  But as long as the confession is still in force, -- and all did not vote for the "Statement," -- the situation is practically unchanged.

\begin{center}
\textsl{But God says:--}
\end{center}

Hos. 3, 9:  "O Israel, thou hast destroyed thyself, but in Me is thine help."  

John 1, 39:  "Behold the Lamb of God, which taketh away the sins of _the world_."

Titus 2, 11:  "For the grace of God that bringeth salvation hath appeared to _all men_."  (2 Pet. 2, 1.)

\textsc{Note.} -- The error of Calvinism does not only consist in denying an election _in Christ_, but especially in teaching an _election to perdition_.  The Lutheran Church teaches, according to Scripture, that there is an election unto salvation, but _not_ unto condemnation.  The _Formula of Concord_ (XI, 5) says:  "But the eternal election of God, or predestination, _i. e._, God's appointment to salvation, pertains not at the same time to the godly and the wicked, _but only to the children of God_."

On an other phase of this mysterious question we will let _Dr. Martin Chemintz_ speak.  He was not only the author of the Eleventh Article in the _Formula of Concord_, but, at the time of its composition, superintendant of the churches of Braunschweig.  In his _Enchiridion_, a work written especially for the instructino of the clergy in his diocese, he puts the following question:  "Does God make such election first after a time, as when men have become penitent and believers, or is it made on account of their piety which God foresees?"  _Answer_:  "St. Paul says in Eph. 1, 4:  'He hath chosen us in Christ before the foundation of the world'; and in 2 Tim. 1, 9:  'He hath saved us, and called us with an holy calling, not according to our works, but according to His own purpose and grace, which was given us in Christ Jesus before the world began.'  Hence, the electino of God does not follow after our faith and righteousness, but goes before them, as a cause of it all.  Moreover, whom He did predestinate, them He also called; and whom He called, them He also justified, Rom. 8, 30.  And in Eph. 1, 4, Paul does not say that we were elected because we _were_ holy or had _become_ holy, but He says:  He hath chosen us that we should _be_ holy.  For predestination is a cause of everything pertaining to salvation, as Paul says:  'We have obtained an inheritance, being predestinated according to the purpose of Him who workth all things after the counsel fo His own will, that we should be to the praise of His glory, who first trusted in Christ.' (Eph. 1, 11. 12.)  And this election is not made in view of our present or future deeds, but according to His own purpose and grace. (Rom. 9; 2 Tim. 1.)"

## Justification
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

Rom. 8, 33:  "Who shall lay anything to the charge of God's elect?  It is God that justifieth."

Gal. 3, 6:  "Even as Abraham believed God, and it was accounted to him for righteousness."

Eph. 2, 8. 9:  "For by grace are ye saved, through faith, and that not of yourselves, it is the gift of God; not of works, lest any man should boast."

Rom. 3, 24:  "Being justified freely by His grace through the recemption that is in Christ Jesus."  3, 28:  "Therefore we conclude that a man is justified by faith, without the deeds of the Law."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Men cannot be justified before God by their own strength, merits, or works, but are freely justified for Christ's sake, through faith, when they believe that they are received into favor, and that their sins are forgiven for Christ's sake, who, by His death, hath made satisfaction for our sins.  This faith God imputes for righteousness in His sight.  (Rom. 3 and 4.)" -- _Augsb. Conf._, Art. IV.

"This article concerning justification by faith is the chief in the entire Christian doctrine, without which no poor conscience has any firm consolation, or can know aright the riches of the grace of Christ, as Dr. Luther also has written:  'If only this article remain in view pure, the Christian Church also remains pure, and is harmonious and without all sects; but if it do not remain pure, it is not possible to resist any error or fanatical spirit.'  And concerning this article Paul especially says that a little leaven leaveneth the whole lump.  Therefore in this article he emphasizes with so much zeal and earnestness the exclusive particles, or the word whereby the works of men are excluded (namely, 'without Law,' 'without works,' 'out of grace' 'freely,' Rom. 3, 28; 4, 5; Eph. 2, 8. 9), in order to indicate how highly necessary it is that in this article, by the side of the presentation of the pure doctrine, the antithesis, _i. e._, all contrary dogmas, by this means be separated, exposed, and rejected...

"Concerning the righteousness of faith before God we unanimously believe, teach, and confess, according to the comprehensive summary of our faith and convession above presented, _viz._, that a poor sinful man is justified before God, _i. e._, absolved and declared free and exempt from all his sins and from the sentence of a well-delivered condemnation, and adopted into sonship and heirship of eternal life, without any merit or worth of his own, also without all preceding, present, or subsequent works, out of pure grace, alone because of the sole merit, complete obedience, bitter suffering, death, and resurrection of our Lord Christ, whose obedience is reckoned to us for righteousness." -- _Form. Conc._, III, 6. 7. 9.

\begin{center}
\textsc{Error.}
\end{center}

1.  The _Catholic Church_, the mother of heresies regarding justification, teaches according to its apologist, J. Adam Moehler:  "The Council of Trent represents justification as a renewal of the inward man, by means whereof we become really just, as inherent in the believer, and as a restoration of the primeval state of humanity.  On this account, the same council observes that by the act of justification, faith, hope, and charity are infused into the heart of man; and that it is only in this way he is truly united with Christ and becometh a living member of His body.  In other words, justification is considered to be sanctification and forgiveness of sins, as the latter is involved in the former, and the former in the latter; it is considered an infusion of the love of God into our hearts through the Holy Spirit; and the interior state of the justified man is regarded as holy feeling, as a sanctified inclination of the will, as habitual pleasure and joy in the divine Law, as a decided and active disposition to fulfil the same in all the occurrences of life, -- in short, as a way of feeling which is in itself acceptable and well pleasing to God." -- _Symbolism_, p. 104.

\textsc{Note.} -- It was on account of this grand confusion of "infusion," "sanctification," "feeling," and "inclination" that Luther could find no "joy in the divine Law" nor peace in the Catholic Church.  This came to him only after learning the meaning of Paul's words:  "Justified by faith, we have peace with God through our Lord Jesus Christ."  (Rom. 5, 1.)

2.  To receive salvation through grace alone is repugnant to self-seeking, guilt-feeling human nature.  Hence not only the pope, but many others have invented schemes of salvation which also include more or less of human efforts.  As representatives of these may be mentioned the _Arminians\index{Arminians}_.  Their celebrated teacher Limborch writes:  "Be it known that we, when we state that we are justified through faith, do not exclude works, but rather include them." -- _Chr. Theol._, VI, 4, 22.

The _Quakers_, representing more nearly our every-day, mushroom religious reformers, teach "that we cannot, as some Protestants unwisely have done, exclude good works from justification.  They are absolutely necessary, forsooth, not as a case on account of which we are justified, but as something _in_ which we are justified, and without which we cannot be justified." -- _Barclay_, _Apol._, 7, 3. 4.

\textsc{Note.} -- Theoretically, the Reformed sects confess justification by faith alone, but to a large extent their every-day religion is Arminianism pure and simple.  

\begin{center}
\textsl{But God says:--}
\end{center}

Gal. 2, 16:  "Knowing that a man is not justified by works of the Law, but by the faith of Jesus Christ."

Rom. 4, 4. 5:  "Now to him that worketh is the reward not reckoned of grace, but of debt.  But to him that worketh not, but believeth on Him that justifieth the ungodly, his faith is counted for righteousness."

Rom. 11, 6:  "And if by grace, then is it no more of works; otherwise grace is no more grace.  But if it be of works, then it is no more grace; otherwise work is no more work."

Rom. 5, 1:  "Being justified by faith, we have peace with God through our Lord Jesus Christ."

Rom. 1, 17:  "The just shall live by faith."

Gal. 3, 26:  "For ye are all the children of God by faith in Christ Jesus."

\textsc{Note.} -- Though Christ expressly promises all those "who hunger and thirst after righteousness that they shall be filled" (Matt. 5, 6), yet the _Catholic Church_ would have its members dougt that any one can come to any certainty in the matter.  No wonder "good" Catholics are willing to pay for indulgences and the reading of masses.

However, the _Methodists_ have a touch of the same sickness.  Their revival preachers, especially, do not direct the occupants of "the anxious seat," or "mourners' bench," to the precious promises of the Lord in His Word, but to their own feeling.  And this feeling is created by "hard praying," shouting, and singing, until the "subject" hysterically shouts for joy.  He is then declared "saved."

\textsl{But God says:--}

John 14, 27:  "Peace I leave with you, My peace I give unto you.  Not as the world giveth, give I unto you.  Let not your heart be troubled, neither let it be afraid."

John 20, 29:  "Blessed are they that have not seen, and yet have believed."

1 John 3, 20:  "For if our heart condemn us, God is greater than our heart, and knoweth all things."

John 4, 46-53:  The nobleman at Capernaum simply clung to the words of Christ:  "Go thy way; thy son liveth."  "And himself believed, and his whole house."

\textsc{Note.} -- _Calvinists_ of whatever name (Presbyterian, Congregational, Baptist) do not only teach that Christ died only for the elect, but also that these alone receive the justifying faith, which they can never wholly lose.

This is emphatically disproved by the example of David and Peter.  Both certainly fell from grace, and fell deeply, but were again restored.

Paul bemoans the fall of Demas, counsels earnestly the exclusion of the fornicator at Corinth, but recommends him to adoption again after he had become penitent.

## Sanctification
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

a.  Perfect holiness cannot be obtained during our natural life.

Phil. 3, 12:  "Not as though I had already attained, either were already perfect:  but I follow after, if I may apprehend that for which also I am apprehended of Christ Jesus."  (Comp. v. 13.)

1 Thess. 4, 1:  "As ye have received of us how ye ought to walk and to please God, _so ye would abound more and more_."

Gal. 5, 17:  "For the flesh lusteth against the spirit, and the spirit against the flesh; and these are contrary the one to the other, so that ye cannot do the things that ye would."  (Heb. 12, 1.)

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"But since in this life believers have not been renewed perfectly or completely (for although their sins are covered by the perfect obedience of Christ, so that they are not imputed to believers for condemnation, and also, through the Holy Ghost, the mortificatino of the old Adam and the renewal in the spirit of their mind in begun), nevertheless the old Adam always clings to them in their nature and all its internal and external powers.  Of this the apostle has written:  'I know that in me (that is, in my flesh) dwelleth no good thing.' (Rom. 7, 18.)  And again:  'For that which I do I allow not; for what I would, that do I not; but what I hate, that do I.'  Again:  'I see another law in my members, warring against the law of my mind, and bringing me into captivity to the law of sin.'  Also:  'The flesh lusteth against the spirit, and the spirit against the flesh; and these are contrary the one to the other, so that ye cannot do the things that ye would.'

"Therefore, because of these lusts of the flesh, the truly believing, elect, and regenerate children of God require not only the daily instruction and admonition, warning, and threatening, of the Law, but also frequently reproofs, whereby they are roused and follow the Spirit of God.  (Ps. 19, 71; 1 Cor. 9, 27; Heb. 12, 8.)" -- _Form. Conc._, VI, 7-9.

\begin{center}
\textsc{Error.}
\end{center}

_Catholics_ and _Methodists_ both teach complete perfection.  The former even claim that, by living up to their monastic vows, monks or nuns may attain such perfection that they are able to _sell_ to others from their superabundant stock of holiness.  This "stock" is handled by "the Church," and sold to the needy, according to the Bull _Unigenitus_ of Pope Clement VI.

But the _Methodists_ do not lag far behind.  Wesley has written a special treatise on "Christian Perfection," a standard work among Methodists to this day, in which he maintains that "a Methodist is one who loves the Lord God with _all_ his heart, with _all_ his soul, with _all_ his mind, with _all_ his strength."  (§ 10.)  "But whom do you mean by 'one that is perfect'?  We mean one in whom is 'the mind which was in Christ,' one 'who so walketh as Christ also walked'; a man 'that hath clean hands and a pure heart,' or that is 'cleansed from all filthiness of flesh and spirit'; one in whom is 'no occasion of stumbling,' and who, accordingly, 'does not commit sin.'"  (§ 15, 4.)  In his _Smaller Catechism_ Dr. W. Nast says:  "Can and must a child of God, in this life, be cleansed from all sin?  Yes.  God's command is:  'Ye shall be holy, for I am holy'; and His promise is that, if we confess our sins, He will cleanse us from all unrighteousness, 1 John 1, 9."

\begin{center}
\textsl{But God says:--}
\end{center}

Jas. 3, 2:  "For in many things we offend all."

Matt. 6, 12:  "Forgive us our trespasses," etc.

Eccl. 7, 20:  "For there is not a just man upon earth, that doeth good and sinneth not."

Prov. 20, 9:  "Who can say, I have made my heart clean, I am pure from my sin?"

1 John 1, 8:  "IF we say that we have no sin, we deceive ourselves, and the truth is not in us."

Gal. 5, 17:  "For the flesh lusteth against the spirit, and the spirit against the flesh; and these are contrary the one to the other, so that ye cannot do the things that ye would."

\begin{center}
\textsc{Bible Doctrine.}
\end{center}

b.  Deeds acceptable to God can be done by believers only.

John 15, 5:  "I am the Vine, ye are the branches.  He that abideth in Me, and I in him, the same bringeth forth much fruit; for without Me ye can do nothing."

Rom. 14, 23:  "Whatsoever is not of faith is sin."

Heb. 11, 6:  "But without faith it is impossible to please Him; for he that cometh to God must bleieve that He is, and that He is a rewarder of them that diligently seek him."

Matt. 12, 33:  "For the tree is known by its fruit."

Gal. 5, 22. 23:  "But the fruit of the Spirit is love, joy, peace, long-suffering, gentleness, goodness, faith, meekness, temperance."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"It is God's will, regulation, and command that believers should walk in good works; and that truly good works are not those which every one, with a good intention, himself contrives, or which are done according to human ordinances, but those which God Himself has prescribed and commanded in His Word.  Also that truly good works are done, not from our own natural powers, but when by faith the person is reconciled with God, and renewed by the Holy Spirit, or (as Paul says) 'created anew in Christ Jesus to good works,' Eph. 2, 10." -- _Form. Conc._, IV, 7.

\begin{center}
\textsc{Error.}
\end{center}

That the semipelagian _Catholic Church_, whose chief hope of salvation rests on human efforts, is the chief offender in this point, goes without saying.  At the Council of Trent the following canon was accepted:  "Whoever says that all deeds done before justification - be they of one kind of another - are truly sins, or merit the wrath of God; or who teaches that the more earnestly one strives to make himself qualified for grace, the more he sins; may he be cursed."  (Sess. 6, 7.) - To this _Chemnitz_ in his _Examen_, replies:  "If the deeds in themselves are not sinful, how do they become so?  I answer:  The heart as GOd's creation is good, but is, on account of sin, nevertheless called evil.  In like manner, deeds which not in themselves are evil become befouled and defiled with the unbeliever, because theya re done by people who are not reconciled with God, nor born again, but are full of guilt and sin.  For God does not judge according to outward appearance, but according to the state of the heart."  "The so-called virtues of unbelievers are not good deeds, but sins, for two reasons:  First, as to their _intention_.  It is a notable saying of St. Augustine that not the deed, but the purpose of the deed, decides virtue and vice.  For, he says, true virtues are services rendered God in the children of man and the gifts of God in the children of men.  Secondly, there is no good fruit which has not grown on the root of love.  But love, according to Gal. 5, 22, is the fruit of the Spirit.  But this is lacking in them that are not born again.  Therefore their good deeds cannot be rated as virtues.  A foul tree can bear only foul fruit, that is, sins only.  Or according to St. Augustine:  'Whatsoever is not of faith is sin, Rom. 14, 23.  This is not to be understood of meats alone (he says) but it is a general truth.'" - Bendixen Ed., 92. 93.

This elucidation is at the present time of special value, since we are so often told of "moral life," "moral uplift," "moral force," etc., where the condition is only common decency - or hidden indecency.

\begin{center}
\textsc{Bible Doctrine.}
\end{center}

c.  That Christ might fulfil all righteousness, He also _preached_ the Law as well as the Gospel; but He was _not a new lawgiver_.

John 1, 17:  "For the Law was given by Moses, but grace and truth came by Jesus Christ."

Luke 4, 18. 19. 21 (Jesus reads Is. 61, 1-3):  "'The Spirit of the Lord is upon Me, because He hath annointed Me to preach the Gospel to the poor; He hath sent Me to heal the broken-hearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised, to preach the acceptable year of the Lord.'  This day is the scripture fulfilled in your ears."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Some theologians or monks ahve taught us to seek remission of sins, grace, and righteousness through our own works and new forms of worship, which have obscured the office of Christ, and have made out of Christ, not a propitiator and justifier, but only a legislator." -- _Apol_., III, 271.

"The adversaries feign that Paul abolishes the Law of Moses, and that Christ succeeds as a new lawgiver in such a way that He does not freely grant the remission of sins, but on account of the works of other laws, if any are now desired... Christ has not succeeded Moses in such a way as on account of our works to remit our sins, but so as to set His own merits and His own propitiation on our behalf over against God's wrath, that we may be freely forgiven."  _Apol_. XIII, 15, 17.

"The adversaries feign that Paul abolishes the Law of Moses, and that Christ succeeds as a new lawgiver in such a way that He does not freely grant the remission of sins, but on account of the work of other laws, if any are now desired.... Christ has not succeeded Moses in such a way as on account of our works to remit sins, but so as to set His own merits and His own propitiation on our behalf over against God's wrath, that we may be freely forgiven." -- _Apol._, XIII, 15, 17.

\begin{center}
\textsc{Error.}
\end{center}

It is the general belief in the _Reformed sects_, that Christ, in the Sermon on the count (Matt. 5-7), has given us "a new code of ethics," and that those who live according to it are sure of heaven.  (Why then the atonement?)

The _Roman Catholic Church_ not only calls Christ a new lawgiver, but also _curses_ those who deny it.  (_Council of Trent_, Sess. 6, can. 21.)

The _Methodists_ claim that Christ made an "addition to the Ten Commandments."  (Cat., No. 3.)

\begin{center}
\textsl{But God says:--}
\end{center}

Gal. 3, 24:  "The Law was our schoolmaster to bring us unto Christ, that we might be justified by faith."  (4, 4. 5.)

John 5, 45:  "Do not think that I will accuse you to the Father; there is one that accuseth you, even Moses, in whom ye trust."  (3, 17.)

Gal. 3, 10:  "Christ hath redeemed us from the curse of the Law."  (Why then "an addition"?)

\begin{center}
\textsc{Bible Doctrine.}
\end{center}

d.  The rule by which all deeds must be judged is the Moral Law.  

Deut. 12, 32:  "What thing soever I command you, observe to do it.  Thou shalt not add thereto, nor diminish from it."  (5, 32.)

Prov. 30, 6:  "Add thou not unto His words, lest He reprove thee, and thou be found a liar."

2 Tim. 3, 16. 17:  "All Scripture is profitable ... to make the man of GOd perfect, thoroughly furnished unto all good works."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"This doctrine of the Law is needful for believers, in order that they may not depend upon their own holiness and devotion, and under the pretext of the Spirit of God establish a self-chosen form of divine worship, without God's Word and command, as it is written:  'Ye shall not do ... every man whatsoever is right in his own eyes,' etc., but 'observe and hear all these words which I command thee.'  'Thou shalt not add thereunto, nor diminish therefrom.'  (Deut. 12, 8. 28. 32.)" -- _Form Conc._, VI, 20.

\begin{center}
\textsc{Error.}
\end{center}

Besides the _Catholics_, with their doctrine of evangelical counsels and consequent superabundant works, the worst errorists in this doctrine are the Romanizing, legalistic, and pietistic _Methodists_.  Who has not heard the claim that traveling on Sunday, indulging in innocent recreation, smoking, as well as every use of liquor, are reprehensible, sinful acts?  (See _Doctrines and Discipline_, chaps. 2. 3.)

Nearly all Reformed sects are prone to legalism, and try to serve GOd through the commandments of men.  (Matt. 15, 9.)

\begin{center}
\textsl{But God says:--}
\end{center}

Col. 2, 16-23:  "Let no man, therefore, judge you in meat, or in drink, or in respect of an holy-day, or of the new moon, or of the Sabbath days; which are a shadow of things to come; but the body is of Christ.  Let no man beguile you of your reward, in a voluntary humility and worshipping of angels, intruding into those things which he hath not seen, vainly puffed up by his fleshly mind, and not holding the Head, from which all the body by joints and bands have nourishment ministered, and knit together, increaseth with the increase of GOd.  Wherefore, if ye be dead with Christ from the rudiments of the world, why, as though living in the world, are ye subject to ordinances (touch not; taste not; handle not; which are to perish with the using), after the commandments and doctrines of men?  Which things have indeed a show of wisdom in will-worship, and humility, and neglecting of the body, not in any honor to the satisfying of the flesh."

1 Tim. 4, 1-5:  "Now the Spirit speaketh expressly that in the latter times some shall depart from the fiaht, giving heed to seducing spirits and doctrines of devils; speaking lies in hypocrisy; having their consciences seared with a hot iron; forbidding to marry, and commanding to abstain from meats, which God hath created to be received with thanksgiving of them which believe and know the truth.  For every creature of God is good, and nothing to be refused if it be received with thanksgiving; for it is sanctified by the Word of God and prayer."  

\begin{center}
\textsc{Bible Doctrine.}
\end{center}

e.  No one becomes a Christian through good deeds, but no one can ignore the diving Law and remain a Christian.

Titus 3, 5:  "Not by works of righteousness which we have done, but according to His mercy He saved us."

Rom. 3, 20. 28:  "Therefore, by the deeds of the Law there shall no flesh be justified in His sight.  Therefore we conclude that a man is justified by faith, without the deeds of the Law."

Matt. 5, 16:  "Let your light so shine before men that they may see your good works, and glorify your Father which is in heaven."  

Eph. 2, 10:  "For we are His workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."  

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"We teach that it is necessary to do good works; not that we may trust that we deserve grace by them, but because it is the will of God that we should do them.  By faith alone is apprehended remission of sins and grace.  And because the Holy Spirit is received by faith, our hearts are now renewed, and so put on new affections, so that they are able to bring forth good works." -- _Augsb. Conf._, XX, 27-29.

The reason for doing good works _Chemnitz_ explains as follows:  "Such are not urged or done as though it were necessary to augment or replace the righteousness or salvation of Christ, which we accept by faith.  For righteousness and salvation must be present before a single good deed can be done.  The tree must be good before it can bring forth good fruit.  (Matt. 12, 33.)  Thus, necessarily, good fruit will follow where there is true faith, righteousness, and salvation.  Where, therefore, no good fruit follows, there we have a sure sign that faith is not of the right kind, and that righteousness and salvation are not present, but have been lost.  (1 Tim. 5, 8; 2 Pet. 1, 9; 1 John 3, 10. 24.)

"_Urban Rhegius_ summarizes the whole thus:  'We should do good works,--

1. Because it is a debt of obedience which we owe, and are commanded to do, to God; also a thanksgiving for His goodness and an offering pleasing to God.

2.  That the heavenly Father may be praised by them.

3.  That our faith through them may be strengthened and increased.

4.  That our fellow-men through them may be incited to do good, and receive help in distress.

5.  That our fiath through them may be shown and proved, our calling made sure, and our faith proved not to be false or dead.

6.  Because our good deeds, though not meriting forgiveness of sin and salvation, have promise both of temporal and eternal reward.  (1 Tim. 4, 8.)'" -- _Chemn., Enchiridion_.

\begin{center}
\textsc{Error.}
\end{center}

1.  All antichristian sects, such as _Socinians, Unitarians, Mormons, Seventh-day Adventists_\index{Adventists}.  Denying the atonement of Christ, they must have "something religious" to fall back on.  But why even that?  If either all are saved at last, or the so-called wicked utterly destroyed, who would really battle "to be good"?  Their dictum of "good deeds necessary to salvation" is, therefore, only a proof of the truth that "conscience makes cowards of us all."

2.  The _Catholic Church_, from from _the average sectarian_, wittingly or unwittingly, has absorbed that pernicious mixture of Law and Gospel which characterizes the Roman system.

The _Decrees of Trent_ declare (Sess. 6, c. 16):  "As a constant power flows from Christ, the Head, on the justified, who are His members, as from the vine to its branches, a power which precedes their good works, accompanies the same, and follows them, -- a power without which they can be in no wise agreeable to God and meritorious, so we are bound to believe that the justified are enabled, through works performed in God, to satisfy the divine Law, according to the conditions of this present life, and to _merit eternal life_, when they depart in a state of grace." -- _J. A. Moehler's Symbolism_, 158.

\begin{center}
\textsl{But God says:--}
\end{center}

Heb. 2, 4:  "The just shall live _by his faith_."

Gal. 3, 10. 11:  "For as many as are of the works of the Law are under the curse.  But that no man is justified by the Law in the sight of God it is evident; for, The just shall live by faith."

Rom. 7, 18:  "For I know that in me, that is, in my flesh, dwelleth no good thing; for to will is present with me, but how to perform that which is good I find not."

Is. 64, 6:  "But we are all as an unclean thing, and all our righteousnesses are as filthy rags."

Ps. 143, 2:  "Enter not into judgment with Thy servant; for in Thy sight shall no man living be justified."  (Luke 17, 10.)

1 Cor. 4, 15:  "In Christ Jesus I have begotten you through the Gospel."

Jas. 1, 18. 21:  "Of His own will begot He us with the Word of Truth, that we should be a kind of first-fruits of His creatures.  Wherefore ... receive with meekness the engrafted Word, which is able to save your souls."

Jer. 23, 29:  "Is not My Word like as a fire? saith the Lord, and like a hammer that breaketh the rock in pieces?"

1 Cor. 1, 18:  "For the preaching of the Cross is to them that perish foolishness, but unto us which are saved _it is the power of God_."

## The Means of Grace
\begin{center}
\textbf{A.  What Are the Means of Grace?}

\textsc{Bible Doctrine.}
\end{center}

The only means through which God has promised to bless mankind are the so-called means of grace, His holy Word and the Sacraments.

John 6, 63:  "The words that I speak unto you, they are Spirit, and they are life."

Heb. 4, 12:  "The Word of God is quick, and powerful, and sharper than any two-edged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart."

Rom. 1, 16:  "The Gospel of Christ is a power of God unto salvation to every one that believeth."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"For the obtaining of this faith the ministry of teachign the Gospel and administering the Sacraments was instituted.  For by the Word and Sacraments, as by instruments, the Holy Spirit is given, who worketh faith, where and when it pleaseth God, in those that hear the Gospel." -- _Augsb. Conf._, V, 1. 2.

"In those things which concern the spoken outward Word, we must firmly hold that GOd grants His Spirit or grace to no one except through or with the preceeding outward Word.  Thereby we are protected against enthusiasts, _i. e._, spirits who boast that they have the Spirit without and before the Word."  _Smalc. Art._, III, 10, 33.

\begin{center}
\textsc{Error.}
\end{center}

1.  The whole army of _Reformed_ teachers from _Zwingli_ to _"Billy" Sunday_, denies, in word and in deed, that the Scripture and the Sacraments are vehicles through which God bestows His grace on mankind.  _Calvin\index{Calvin}_ calls the Word "a sound only, that has effect, not because of its being spoken (or used), but because it is believed" (_Inst._, IV, 14, 4).  _Zwingli_ says in his _Reckoning of Faith_:  "I believe, yea I know, that all the Sacraments are so far from conferring grace that they do not even convey or distribute it.... Moreover, a channel or vehicle is not necessary to the Spirit; for He Himself is the virtue and energy, whereby all things are borne, and has no need of being borne."  (§ 7.)

2.  According to _Methodism_ "The means of grace are either instituted or prudential."  The instituded are "prayer, searching the Scriptures, the Lord's Supper, fasting, and Christian conference."  (_Doctr. and Discipl._, §§ 118-122.)  According to this explanation everything enjoined in Scripture is a means of grace, _e. g._, the Ten Commandments with their deeper, spiritual explanation, as found in ther Sermon on the Mount, Matt. 5-7!  Of the Sacraments the _Methodists_ say:  "A Sacrament is an outward and visible _sign_ of an inward and spiritual grace."  -- _Cat,_, No. 3.

3.  The _Episcopal\index{Episcopal Church} Church_ teaches that "Sacraments ordained of Christ be not only badges or tokens of Christian men's profession, but rather they be certain sure witnesses, and effectual _signs of grace_, and GOd's good will towards us, by which He doth work invisibly in us, and doth not only quicken, but also strengthen and confirm, our faith in Him."  (_Art. of Rel._, XXV.)  The _Reformed Episocopal\index{Episcopal Church} Church_ expressly states that it wants the word "Sacrament to mean only a symbol or sign instituted by God."  (Art. 25.)

4.  _Presbyterians_ and _Congregationalists\index{Congregationalists}_ confess:  "Sacraments are holy _signs_ and seals of the covenant of grace, immediately instituted by God, to represent Christ and His benefits, and to confirm our interest in Him, as also to put a visible difference between those that belong unto the Church and the rest of the world, and solemnly to engage them to the service of God in Christ, according to His Word." -- Chap. XXVII, 1.  _Savoy Decl._, chap. XXVIII.

\textsc{Note. --} The Lutheran Church also calls the Sacraments "signs," but _not only_ that.  Primarily they are _means_ through which God gives His grace.  The Word of God as a whole is such an effective means; why, then, should not the words of institution in the Sacraments be so?

"Christ has instituted the Sacraments for thereby to strengthen and preserve our faith.  Our hearts have difficulty in holding fast to the Word alone.  So, when it is proclaimed for all in general, our conscience vexes us with questions, whether God also means me, or, if I also, I personally, may accept it and console myself with it.  Therefore Christ, being rich in mercy, instituted such outward, visible Sacraments, in and through which, as through visible, public evidences, He wishes to deal with us, that we may have a sure seal and bond that the primises of the Gospel concern eacn and every one personally, and that He may effectively apply, make sure, and seal such truth in the hearts of all those who use the Sacraments in true faith.  And there is no doubting that the Son of God, through these means, works mightily to strengthen and preserve the faith in the believers.  Consequently, the Sacramentarians are rightly rejected, who hold that the Sacraments are only outward signs that only indicate or signify something." -- _Enchiridion_, Chemnitz.

Since the twelfth century, the Catholic Church has held that there are seven Sacraments:  Baptism, Confirmation, the Lord's Supper, Penance, Orders (Priesthood, etc.), Marriage, and Extreme Unction.  In their consecration of bells, lights, water, etc., formulas are used "which presuppose a magical effect."

\begin{center}
\textsl{But God says:--}
\end{center}

Is. 55, 10. 11:  "For as the rain cometh down, and the snow, from heaven, and returneth not thither, but watereth the earth, and maketh it bring forth and bud, that it may give seed to the sower and bread to the eater, so shall My Word be that goeth forth out of My mouth:  it shall not return unto Me void, but _it shall accomplish_ that which I please, and it shall prosper in the thing whereto I sent it."  (Luke 11, 28.)

John 6, 68:  "Lord, to whom shall we go?  Thou hast the _words of eternal life_."

1 Pet. 1, 23:  "being born again, not of corruptible seed, but of incorruptible, _by the Word of God_, which liveth and abideth forever."  (Rom. 10, 6-8.)

\begin{center}
\textbf{B.  Efficacy of the Means of Grace.}

\textsc{Bible Doctrine.}
\end{center}

The means of grace are effective regardless of the attitude of the administrator towards God.

Matt. 23, 2. 3:  "The scribes and the PHarisees sit in Moses' seat.  All, therefore, whatsoever they bid you observe, that observe and do; but do not ye after their words; for they say, and do not."  (Rom. 2, 21. 23.)

\begin{center}
\textsl{Lutheran Testimony.}
\end{center}

"Though the Church be properly the congregation of saints and true believers, yet, seeing that in this life many hypocrites and evil persons are mingled with it, it is lawful to use the Sacraments administered by evil men, according to the voice of Christ:  'The scribes and the Pharisees sit in Moses' seat,' and the words following.  And the Sacraments of the Word are effectual by reason of the institution and commandment of Christ, though they be delivered by evil men.  They condemn the Donatists\index{Donatists} and such like, who denied that it was lawful to use the ministry of evil men in the Church and held that the ministry of evil men is useless and without effect." -- _Aubsb. Conf._, VIII

\begin{center}
\textsc{Error.}
\end{center}

The _Donatists_\index{Donatists}, like the Pharisees, are an ever-present race.  And they are not confined to any particular denomination.  Churches of the _Methodistic_ order suffer most, but all have their share, even the Lutheran Church.  The usual charge is that the poor state of the Church, as well as society, must be charged to the account of the unconverted clergy; for "if ministers spake from the heart, their message would go to the heart."

But history and experience tell a different story, as the following shows.

1.  Ministers are only deliverers of a message.  The message, not the messenger, is the instrument of power.

2.  God alone judges the heart rightly.  The error committed by the prophet Elijah in passing judgment on his fellow-man should make us all pause.  

3.  Noah, the mighty "preacher of righteousness" (2 Pet. 2, 5.), was certainly zealous in the cause of God, but he did not convert even the builders of the Ark.

4.  The prophets of old were burning in their zeal for the conversion of sinners, but were stoned for their labors.

5.  John the Baptist labored largely in vain.  And the fate of Christ's apostles is familiar to all.  And yet, no one since their day has had the Spirit in such a measure as they.

It is true:  "There is no more contemptible creature on earth than an unconverted preacher." -- But the efficacy of the means of grace does not depend upon the converted condition of the clergyman.

\begin{center}
\textsl{But God says:--}
\end{center}

Phil. 1, 15-18:  "Some, indeed, preach Christ even of envy and strife, and some also of good will.  The one preaches Christ of contention, not sincerely, supposing to add afflictions to my bonds; but the other of love, knowing that I am set for the defense of the Gospel.  What then?  Notwithstanding, ever way, whether in pretense or in truth, Christ is preached; and I therein do rejoice, yes, and will rejoice."

\textsc{Note. 1. --} The doctrine concerning the means of grace is not only clearly taught in the Scriptures, but is also of _vital importance_ to the penitent sinner.  He hears much about the "testimony of the Spirit," the "baptism of fire," and that the "Spirit" is the cause of every religious movement, from Zwinglianism to Dowieism.  But as all these "isms" in many instances bear witness _against_ one another, the "Spirit' is either unreliable, or it is not the _right_ Spirit.  Hence a _rule_ of faith and a _means_ through which God _gives_ faith, _according_ to this rule, is of the highest importance.  This we have in the Gospel.  

\textsc{Note. 2. --} The reading of the Bible among the lay people of the Protestant Church is not only permitted, but urgently recommended.  in the Catholic Church, however, lay people must have a "permit" before they can get a Bible, and then only the Catholic version, or edition, which has several incorrectly translated passages (favorable to Rome, and hence never righted) and numerous explanatory notes (also favorable to Rome).  Catholic laymen are never allowed to read or own a Protestant Bible.  Hence we to this day hear of Bibles being burned by Catholic priests.

\begin{center}
\textbf{Baptism\index{Baptism}.}

\textsl{1.  What Is Baptism?}

\textsc{Bible Doctrine.}
\end{center}

Baptism is a sacramental institution of God, through which He effects regeneration and grants forgiveness of sin.

Matt. 28, 19. 20:  "Go ye, therefore, and _make disciples of all the nations_, baptizing them in the name of the Father and of the Son and of the Holy Ghost; teaching them to observe all things whatsoever I have commanded you.  And lo, I am with you alway, even unto the end of the world." 

Gal. 3, 26:  "For ye are all the children of God by faith in Christ Jesus.  For as many of you as have been baptized into Christ have _put on Christ_."

Acts 2, 38:  "Repent ye, and be baptized, every one of you, in the name of Jesus Christ _unto the remission of your sins_, and ye shall receive the gift of the Holy Ghost."

John 3, 5:  "Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot _enter into the kingdom of God_."

Titus 3, 5-7:  "Not by works of righteousness which we have done, but according to His mercy _He saved us, by the washing of regeneration_ and renewing of the Holy Ghost, which He shed on us abundantly through Jesus Christ, our Savior, that, being justified by His grace, we should be made heirs according to the hope of eternal life."

Eph. 5, 25. 26:  "Christ loved the Church, and gave Himself for it, that He might sanctify and _cleanse it_ with the washing of water by the word."

1 Pet. 3, 20. 21:  "Noah prepared the ark, wherein few, that is, eight souls, _were saved by water; the like figure_ whereunto even _Baptism doth also now save us_ (not the putting away of the filth of the flesh, but the answer of a good conscience toward God), by the resurrection of Jesus Christ."

Col. 2, 11. 12:  "In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ; buried with him in Baptism, _wherein also ye are risen with Him through the faith of the operation of God_; who hath raised Him from the dead."  (Also v. 13, The argument here is:  Baptism has taken the place of circumcision, hence the latter is not necessary.  But as circumcision was administered to children, so Baptism also must be.  And as circumcision converred "burying of sins," so also Baptism.)

Acts 22, 16.  On reciting at Jerusalem the story of his conversion, Paul also relates how the prophet Ananias, at God's command, came to him, saying among other things:  "And now, why tarriest thou?  Arise, and be baptized, and _wash away thy sins_, calling on the name of the Lord."  NB.  When Calvin interprets this passage by saying (_Inst._, IV, 15, 15):  "All, then, that Ananias meant to say was:  Be baptized, Paul, that you may be assured that your sins are forgiven you," this is a fair example of Reformed perversion of Scripture.  

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"In these words [of institution] we must notice, in the first place, that here stands God's commandment and institution that we shall not doubt that Baptism is difine, and not devised and invented by men.  For as truly as I can say no man has spun the Ten Commandments, the Creed, and the Lord's Prayer out of his head, but they are revealed and given by God Himself, so also I can boast that Baptism is no human trifle, but that it is instituted by God Himself, and that it is most solemnly and rididly commanded that we must permit ourselves to be baptized, or we cannot be saved." -- _Large Cat._, IV, 6.

"Since we know now what Baptism is, and how it is to be administered, we must, in the second place, also learn why and for what purpose it is instituted; that is, what it avails, gives, and produces.  And this also we cannot discern better than from the words of Christ above quoted:  'He that believeth and is baptized shall be saved.'  Therefore we state it most simply thus, that the power, work, profit, fruit, and end of Baptism is this, _viz._, to save.  For no one is baptized in order that he may become a prince, but, as the words declare, that he be saved.  But to be saved, we know, is nothing else than to be delivered from sin, death, and the devil, and to enter into the kingdom of Christ, and to live with Him forever." -- _Large Cat._, IV, 23 f.

\begin{center}
\textsc{Error.}
\end{center}

With the Word of God in this doctrine the Lutheran Church stands alone.  _All the others_ follow blind reason, and _declare that Baptism does not effect regeneration, but is only a sign of regeneration, or the new birth_.

_Episcopalians\index{Episcopal Church}_, _Presbyterians_, _Baptists\index{Baptists}_, _Congregationalists\index{Congregationalists}_, and _Methodists_ differ in their confessions about Baptism in language only.  The Presbyterian may be taken as a model:  "Baptism is a Sacrament of the New Testament, ordained by Jesus Christ, not only for the solemn admission of the party baptized into the visible Church, but also to be unto him a _sign and a seal_ of the covenant of grace, of his ingrafting into Christ, of regeneration, of remission of sins, and of his giving up unto God, through Jesus Christ, to walk in newness of life:  which Sacrament is, by Christ's own appointment, to be continued in His Church until the end of the world."  (XXVIII.)

\begin{center}
\textsl{But God says:--}
\end{center}

Rom. 6, 3. 4:  "So many of us as were baptized into Jesus Christ were baptized into His death.  Therefore we are buried with Him by Baptism into death."

1 Cor. 12, 13:  "For in one Spirit were all baptized into one body" (_i. e._, Christ, v. 12).

\textsc{Note. --} The Nicene Creed, § 9, reads:  "I acknowledge one Baptism for the _remission of sins_."

\begin{center}
\textsl{2.  For Whom Is Baptism Instituted?}

\textsc{Bible Doctrine.}
\end{center}

The Sacrament of Baptism is instituted not only for adults, but also for the children.

Matt. 28, 19:  "Go ye, therefore, and teach [make disciples of] _all nations_, baptizing them," etc.

John 3, 5:  "Verily, verily, I say unto thee, Except a man be born of water and the Spirit, he cannot enter into the Kingdom of God."

Acts 16, 14. 15:  "Lydia, a seller of purple, of the city of Thyatira,...was baptized, _and her household_."

Acts 16, 32. 33:  The jailer at Philippi, when converted, was baptized, "_and all his_."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Of Baptism they teach that it is necessary to salvation, and that by Baptism the grace of God is offered, and that children are to be baptized, who, by Baptism being offered to God, are received into God's favor.  They condemn the Anabaptists, who allow not the baptism of children, and affirm that children are saved without Baptism." -- _Augsb. Conf._, Art. IX.

"It is manifest that God approves of the baptism of little children.  Therefore the Anabaptists, who condemn the baptism of little Children, believe wickedly.  That God, however, approves of the baptism of little children is shown by this, _viz._, that God gives the Holy Ghost to those thus baptized.  For if this baptism would be in vain, the Holy Ghost would be given to none, none would be saved, and finally there would be no Church.  This reason, even taken alone, can sufficiently establish good and godly minds against the godless and fanatical opinions of the Anabaptists." -- _Apol. A. C._, IX, 53.

\begin{center}
\textsc{Error.}
\end{center}

The chief offenders against the truth in the doctrine of Baptism are the so-called _Baptists\index{Baptists}_.  In their confession of 1688 they declare that _only_ such are to be baptized as can be truly penitent before God, confess their faith in Christ Jesus, and show their obedience towards Him.  (XZXIX, 2.)  This, they argue, children cannot do, hence they are not to be baptized.

\textsc{Note. --} The doctrine of Baptism has been variously assailed, from the days of the early Church down to the present time.  That Baptism was unnecessary, especially for children, and that only grown persons could have any benefit from it, were early heresies.  Many delayed being baptized until they were on their deathbed, while others repeated the rite several times.  Especially the practice of infant baptism has been assailed by various sects, and is condemned as unscrpitural and unnecessary by some to the present day.

\begin{center}
\textsc{Objections to Infant Baptism Answered.}
\end{center}

_First Objection_. -- When Christ commanded His apostles to " make disciples of all nations," He did not take children into account.

_Answer_. -- A nation is composed of old and young.  Christ does not especially mention children in the command to baptize, because the apostles knew that such were included, even as they were included in the command to circumcise under the Old Testament dispensation.  The Savior emphasizes only two things, _viz_.:  Baptism is to take the place of circumcision, and instead of their working among _one_ nation they should go out among _all_ nations

_Second Objection_. -- In connection with Baptism Christ also speaks of faith.  But to believe is to perform a conscious act, something which infants obviously cannot do.

_Answer_. -- This is not only human reasoning, but faulty reasoning at that.  To believe is to perform a conscious act, _but not always_.  A person who with fear and trepidation presents a petition to his dread monarch has often no hope at all.  His faith is only an ardent desire.  The publican with his petition, Luke 18, 13, the father of the son with a dumb spirit, Mark 9, 24, are examples of such unconscious believers.  And to such Christ ministered, according to the promise of old:  "But to this man will I look, even to him that is poor and of a contrite spirit, and trembleth at My Word."  (Is. 66, 2.)  Again:  Without faith it is impossible to please God (Heb. 11, 6), and he that believeth not shall be damned (Mark 16, 16).  But if faith is always a conscious act, how could a sleeping person be a Christian?  Or how, then, could a person dying while asleep, or during unconsciousness, escape condemnation?  

Christ solves the seeming mystery best of all.  He says of certain small children that they _believe on Him_ (Matt. 18, 6), and that, if we would enter the kingdom of heaven, we must become as they (v. 3).  At His triumphant entry into Jerusalem He was hailed as King, not only by the adult population, but also by "babes and sucklings" (Matt. 21, 15. 16); and He reproved those who tried to stop them.

_Third Objection_. -- In conjunction with Baptism Christ also enjoins teaching.  And the apostles seem to have followed this practise.  In Acts 2, 41 it is related how only those were baptized who _received the teachings_ of the apostle.  "Babes and sucklings" cannot thus be instructed.

_Answer_. -- The practise of the apostles is neither here nor elsewhere fully described.  But it is preposterous to conclude that among the families baptized on Pentecost there should have been no children.  Likewise, when it is related in Acts 16 that "Lydia and her household were baptized," also the keeper of the prison at Philippi "and all his," we rightly conclude that children were included.  And certainly the contrary cannot be established.  (See also Acts 18, 8; 1 Cor. 1, 16.)

The older translation of the Bible is much to blame for the view that baptism must follow teaching only.  If the reading, "Go ye and teach all nations," in Matt. 28, 19, had been rendered, "Go ye and make disciples of all nations, baptizing them," etc., as the original Greek has it, many a sincere truth-seeker would not have fallen a prey to designing proselyters.  

_Fourth Objection_. -- There is no way in which we can communicate with, or exert influence on, the soul of a child; hence anything that we may do is of no avail.

_Answer_. -- A bud is not the flower in full bloom, and yet the whole flower is in the bud.  The suckling is not very old before, like a bud, it unfolds its latent powers.  Besides, it is not man who influences the soul of a child, -- or an adult's, for that matter, -- but God, through His means of grace.

Of Jeremiah God says:  "Before I formed thee, I knew thee; before thou camest forth, I sanctified thee."  (Jer. 1, 5.)  And of John the Baptist:  "He shall be filled with the Holy Ghost, even from his mother's womb."  (Luke 1, 15.)

The point here is not that the Lord gave these two children the Holy Ghost, but that they received it _earlier than others_, who received it on the eighth day after their birth, at _circumcision_.  For as Abraham received the sign of circumcision as a seal of righteousness of faith (Rom. 4, 11), so this same sign became the same seal unto the _children_ who were circumcised.  In like manner GOd now, through Baptism, als influences the child's spiritual life, and gives it the Holy Ghost.

_Fifth Objection_. -- The children at birth have no need of being influenced by God or man; for according to Rom. 5, 18, "as by the offense of one judgement came upon all men to condemnation, even so by the righteousness of One the free gift came upon all men unto justification of life"; and this can apply fully only when innocent childhood is taken into account.

_Answer_. -- Only one child born into this world was born without sin.  All others are conceived in sin and shapen in iniquity (Ps. 51, 5); all have sinned, and come short of the glory of God (Rom. 3, 23); and except a man be born again, born of water and of the Spirit, he cannot enter into the kingdom of God (John 3, 3. 5).  

As to Rom. 5, 18, the apostle explains in the preceeding verse how he wishes the declaration, "Free gift came upon all men," understood.  He says:  "For if by the trespasses of the one, death reigned through the one, much more shall they that _receive_ the abundance of grace and of the gift of righteousness reign in life through the One, even Jesus Christ."  There is abundance of grace for all, but only they profit by it who _"receive"_ it, _i. e._, believe it.

The Jews believed that they, as a matter of course, would surely be saved because they were the descendants of Abraham; but the apostle says explicitly:  "They which are of faith, the same are the children of Abraham."  (Gal. 3, 7; Rom. 9, 8.)

_Sixth Objection._ -- Baptism of the Spirit is the only regenerating baptism.  Water-baptism is of no avail.

_Answer_. -- To argue thus is to put asunder what God has joined together.  God is not bound to certain means, it is true, but we are:  and the few examples of God's extraordinary workings are only exceptions that attest the rule.  The apostles on Pentecost promised the remission of sins and the gift of the Holy Ghost only to those who would be baptized.  (Acts 2, 38.)  God could, undoubtedly, kindle faith in man's heart without means, but He has bound us to the use of His Word, and promised salvation only to those who use it and accept it.  (Rom. 10, 8-18.)

To call Christian Baptism "water-baptism" is to talk disrespectully of a divine ordinance.

Naaman the Syrian found fault with the treatment which the prophet Elisha told him to use for his leprosy; but when he listened to counsel and used it, he became clean.  (2 Kings 5.)  When God has ordained the Sacrament of Baptism, and through it gives salvation and the Holy Ghost (Titus 3, 5), it behooves us to praise and give thanks, instead of finding fault.  To say with Calvin that "Spirit and water (John 3, 5) is the same as Spirit which is water" is doing violence to the Scriptures.  (See his _Institutio Rel._, IV, 16, 25.)

_Seventh Objection_. -- The baptism of infants is only a relic of popery, and not sanctioned by apostolic practise.

_Answer_. -- The beginning of popery has no exact date.  Popery is a growth whose roots reach back into the time of the apostles themselves, who often speak of antichristian tendencies.  But historians of merit generally say that "the worshiping of the Beast and his image" (Rev. 14, 9) became unmistakable in the sixth century.  But Baptism was not one of its signs, as the following excerpts clearly show.

_St. Augustine_, bishop of Hippo, † 430, says:  "The whole church practises infant baptism.  It was not instituted by councils, but was always practised."

At the instance of Bishop _St. Cyprian_, † 258, the _Council of Carthage_ (254) decreed that "no one ought to be hindered from Baptism and from the grace of God, who is merciful and kind and loving to all; which, since it is to be observed and maintained in respect of all, we think it is to be even more observed in respect of infants and newly born persons, who on this very account deserve more from our help and from the divine mercy, that immediately ,on the very beginning of their birth, lamenting and weeping, they do nothing else than entreat." -- _Ante-Nicene Fathers_, V, 354.

_Origen_ of Alexandria, † 254, not only testifies that it was according to ancient usage of the Church to "baptize even infants...for the remission of sins," but that such custom had come down "_from the apostles themselves_."

_Tertullian_, † 245, who on account of his heresies really is no church-father, fought infant-baptism, _not_ on account of its unscrpituralness, but because of the danger of falling away from the baptismal vow.  He wanted it done as late in life as possible. -- _Ante-Nicene Fathers_, III, 661 f.

In the so-called _Constitutions of the Holy Apostles_ (erroneously ascribed to Clement of Rome, a disciple of the Apostle Peter), a collection of church rules of not later than the fourth century, we read:  "Do you also baptize your infants, and bring them up in the nurture and admonition of God.  For He says:  'Suffer the little children to come unto Me, and forbid them not.'" -- _Ante-Nicene Fathers_, VII, 457.

_Irenaeus_, bishop of Lyons, who died as a martyr 202, in _Against Heretics_, writes:  "He came to save all through means of Himself -- all, I say, who through Him are born again to God -- _infants and children_, and boys, and youths, and old men."  (_Ante-Nicene Fathers_, I, 391.)  What he means by "born again to God" he tells us further on:  "And again, giving to the disciples _the power or regeneration_ into God, He said to them, 'Go and teach all nations, baptizing them in the name of the Father and of the Son and of the Holy Ghost.'" (444.)

_Justin Martyr_, † 179, in his _First Apology_ (15), speaks of "many, both men and women, who have been Christ's disciples from childhood."  This he explains more fully in chapter 61, on "Christian Baptism":  "Then they are brought by us where there is water, and are regenerated in the same manner in which we ourselves were regenerated." -- _Ante-Nicene Fathers_, I, 167. 183.

During the Pelagian controversy the doctrine of infant baptism also came up for consideration.  After -- or at -- the Council of Carthage, 416, _sixty-eight_ bishops wrote to Bishop Innocent of Rome, and, among other things, pointed out to him that the error of the Pelagians really meant "that infants need not be baptized at all, that they were perfectly innocent and needed no redemption."

_Eighth Objection_. -- Baptism is valid only when done by immersion.

_Answer_. -- This argument from the first illiterate adversaries of infant baptism is, wonderful to relate, still in vogue, especially among Baptists.  At first the Greek word, which has been Anglicized into "baptize," was held to mean "immerse," and nothing else.  Scholars among them must now, of course, acknowledge that such is not the case (as can readily be seen by any one who has but a smattering of Greek, in referring to Matt. 7, 4. 8; 3, 11; Acts 1, 5; 2, 17, etc., etc.), but they cling to the theory just the same. 

Baptism by immersion was undeniably practised in the first few centuries after the apostles, but not by any means exclusively.  _The Teachings of the Twelve Apostles_, a document dating from the second century of the Christian era, has this to say on the mode of baptizing:  "And concerning Baptism, thus baptize ye:  Having first said all these things, baptize into the name of the Father and of the Son and of the Holy Spirit, in living water.  But if thou have not living water, baptize into other water; and if thou canst not in cold, in warm.  But if thou have not either, _pour out water_ thrice upon the head into the name of the Father and Son and Holy Ghost." -- _Ante-Nicene Fathers_, VII, 379.

_Ninth Objection_. -- The repetition of Baptism is not a sin, but a blessing.

_Answer_. -- Since there is no warrant in the Scriptures for the Catholic doctrine of an "indelible character" conferred by Baptism, some fanatics have gone to the other extreme and taught that Baptism ought to be repeated now and then, even as the other Sacrament, the Lord's Supper, is repeated.  

The Lord's Supper is to be repeated because _Christ expressly comands it_.  In the institution of Baptism no such command is added.  IN the whole Bible no instance of repetition is recorded.  The covenant made in Baptism may be broken by man, but not by the Lord.  He who repents and returns to GOd will find the baptismal covenant still in force.

\begin{center}
\textbf{D.  The Office of the Keys, or Absolution\index{Absolution}.}

\textsc{Bible Doctrine.}
\end{center}

_Definition_. -- "Through the office\index{Keys, Office of!zzzzz@\igobble|seealso{Absolution}} of the ministry God has given to the Church the command and power to pass judgment on the unbelieving and impenitent sinner, and, for Christ's sake, to absolve the believing and penitent." -- _Chemnitz_, _Enchir. and Ex._

Matt. 16, 19:  "Whatsoever thou shalt bind on earth shall be bound in heaven, and whatsoever thou shalt lose on earth shall be loosed in heaven."

John 20, 23 (to all the disciples):  "Whosoever sins ye remit, they are remitted unto them, and whosoever sins ye retain, they are retained." 

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"Men are taught that they should highly regard absolution, inasmuch as it is God's voice, and pronounced by God's command." -- _Augsb. Conf._, Art. 25, 3.

"Now, their judgment is this:  that the power of the keys, or the power of the bishops, by the rule of the Gospel, is a power, or commandment, from God of preaching the Gospel, of remitting or retaining sins, and of administering the Sacraments." -- _Augsb. Conf._, Art. 28, 5.

"In addition to this it is necessary to confess that the keys pertain not to the person of a particular man, but to the Church, as many most clear and firm arguments testify.  For Christ, speaking concerning the keys (Matt. 18, 19), adds:  'If two of you shall agree on earth, as touching anything that they shall ask, it shall be done for them of My Father which is in heaven.'  Therefore He ascribes the keys to the Church principally and immediately, just as also for this reason the Church has principally the right of calling.  For just as the promise of the Gospel belongs certainly and immediately to the entire Church, because the keys are nothing else than the office whereby this promise is communicated to every one who desires it, just as it is actually manifest that the Church has the power to ordain ministers of the Church.  And Christ speaks in these words, 'Whatsoever ye shall bind,' etc., and means that to which He has given the keys, namely, the Church:  'Where two or three are gathered together in My name' (Matt. 18, 20).  Likewise Christ gives supreme and final jurisdiction to the Church when He says:  'Tell it to the Church.'" -- _Smalc. Art._, App., § 24.

"In case of necessity even a layman absolves, and becomes the minister and pastor of another." -- _Ibid_., § 67.

\begin{center}
\textsc{Error.}
\end{center}

1.  The well-known position of the _Catholic Church_, that "no one can enter heaven unless a _priest_ has opened the door" (_Rom. Cat._, II, 5, 43), need here only be mentioned.  And the oft-repeated saying that St. Peter is the doorkeeper of heaven is only a monastic fable.

2.  The _Reformed Churches_, one and all, practise neither private nor public absolution.  Zwingli ridiculed it, and Calvin\index{Calvin} says:  "The power of the keys is simply the preaching of the Gospel,...and in so far as men are concerned, it is not so much power as ministry.  Properly speaking, Christ did not give this power to men, but to His Word, of which He made men the ministers." -- _Instit._, IV, 11, 1.

3.  The _Episcopalians\index{Episcopal Church}_ have substituted for absolution this formula in _Warning for the Celebration of the Holy Communion_:  "If there be any of you who by this means cannot quiet his own conscience herein, but requireth further comfort or counsel, let him come to me, or to some other minister of God's Word, and open his grief that he may receive such godly counsel and advice as may tend to the quieting of his conscience and the removing of all scruple and doubtfulness." -- _Book of Com. Prayer_, Exhort.

4.  The _Presbyterians_ speak only of "Church Censure" (_Westm. Conf._, XXX), and the _Methodists_ have invented the "class-meeting" with its "class-leader" as a substitute for the ordinance of God. -- _Ch. Discipl._, II, 28.

\textsc{Note. --} The Scriptures speak of the Office of the Keys in a two-fold manner.

1.  When the Word of God is preached, His wrath and condemnation is pronounced on sin and impenitent sinners.  Though the preacher does not know of every sin, nor has any particular sinner in view, yet the sins of the impenitent and unbelieving ar bound and retained in heaven through his preaching.  (Matt. 24:  The Jews were doomed for not accepting the salvation offered.  Luke 10:  Woe was pronounced upon Chorazin, Bethsaida, Capernaum, and the places that would not accept the preaching of the apostles.  Also chap. 13; Acts 13, 40. 41; Eph. 4, 4:  "For this ye know, that no whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God."  2. Thess. 1, 8:  "The Lord Jesus shall come to "take vengance on them that know not God, and that obey not the Gospel of our Lord Jesus Christ.")

2.  When one who is conscience-striken and weak in faith cannot find full consolation in the Word as preached to the Christian congregation, but anxiously asks whether he, the great, unworthy sinner, is included among those towards whom God is gracious or not, or what decree may have been passed upon him in the council of the Most High, to such a one Christ not only in general causes the Gospel to be preached, but in order to augment and strengthen his faith and give him an abiding consolation, He also privately and personally assures him of the forgiveness of sin.  (Cf. Matt. 9; Luke 7, 19. 23.)  And this loosing key, together with its attendant gracious promise, He has given unto His servants to use.  This is commonly called _private absolution_.  (Adapted from Chemnitz's _Enchiridion_.)

\begin{center}
\textbf{E.  The Lord's Supper}

\textsl{1.  What is the Lord's Supper?}

\textsc{Biblical Lutheran Doctrine.}
\end{center}

"The Lord's SUpper is the true body and blood of our Lord Jesus Christ, under the bread and wine, given unto us Christians to eat and to drink, as it was instituted by Christ Himself." -- Matt. 26, 26-28; Mark 14, 22-24; Luke 22, 19. 20; 1 Cor. 11, 23-25.

The Tenth Article in the _Augsburg Confession_ is substantially the same as the above.  In his _Apology_, Melancthon adds:  "We defend the doctrine received in the entire Church, that in the Lord's Supper the body and blood of Christ are truly and substantially present, and are truly tendered with those things which are seen, bread and wine.  And we speak of the presence of the living Christ, knowing that 'death hath no more dominion over Him.'" -- Art. X.

\begin{center}
\textsc{Error.}
\end{center}

1.  _Zwingli_, the father of Reformed rationalism, says in his preface to _A Short Christian Instruction to the Clergy_:  "The Lord's Supper is nothing more than the feast of the soul; and Christ instituted it as a remembrance of Himself.  When man trusts in the suffering and redemption of Christ, he shall be saved.  Of this He has left us a _sure and visible sign_ in the emblems of His body and blood, and entreats us to eat and to drink both in remembrance of Him." -- Winer, Clark's ed., p. 269.  (Compare _Darst._, XVI, 2.)

In his _Reckoning of Faith_ (presented at Augsburg, 1530) this is his standpoint:  "eighthly, I believe that in the Holy Eucharist, _i. e._, the supper of thanksgiving, the true body of Christ is present by the contemplation of faith; _i. e._, that they who thank the Lord for the kindness conferred on us in His Son, acknowledge that He assumed true flesh, in it truly suffered, truly washed away our sins in His own blood; and thus everything done by Christ becomes present to them by the contemplation of faith.  But that the body of Christ in essense and really -- _i. e._, the natural body itself -- is either present in the Supper or masticated with our mouth or teeth, as the papists and some who long for the fleshpots of Egypt assert, we not only deny, but firmly maintain is an error opposed to God's Word." -- Jacobs, _Book of Concord_, I, 170.

2.  _Calvin\index{Calvin}_ says in his _Institutes_:  "How, then, could they [the disciples] have been so ready to believe _what is repugnant to  all reason, viz._, that Christ was seated at table under their eye, and yet was contained invisibly under the bread?" -- IV. C. XVII, § 23.)

3.  _The Heidelberg Catechism_ (by Ursinus and Olevianus, 1563) is the mother confession of all later Reformed confessions.  Of the Eucharist it says:  "The Lord's Supper is a distributing and receiving of bread and wine commanded of Christ unto the faithful, that by _these signs_ He might testify that He has delivered and yielded His body unto death, and has shed His blood for them, and does give them these things to eat and drink, that they might be unto them the meat and drink of eternal life, and that thereby also He might testify that He would dwell in them, nourish and quicken them forever."  (Quest. 75, Ursin's _Explication_; Henry Parry's translation.) -- Again:  "To eat is to believe, to receive remission of sin by faith, to be united to Christ, to be made partakers of the life of Christ."  (Qu. 76.)  Again:  "The literal sense, if it be properly taken, can be _no other wise_ understood than thus:  The substance of this bread is the substance of My body.  But so to understand it is an _undoubted absurdity_."  (Qu. 77.)

4.  _The Book of Common Prayer\index{Book of Common Prayer} (Episcopal)\index{Episcopal Church}_ says in "a catechism...to be learned...before confirmation":  "Why was the Sacrament of the Lord's Supper ordained?  _Ans._:  For the continual remembrance of the sacrifice of the death of Christ, and of the benefits which we receive thereby.  What is the inward part, or thing signified?  _Ans._:  The body and blood fo Christ, which are _spiritually taken and received_ by the faithful in the Lord's Supper."  (p. 228.) -- In the Episcopal _Articles of Religion_, Art. XXVIII speaks in the first part of "partaking of the body and blood of Christ," but concludes by stating that "The body of Christ is given, taken, and eaten, in the Supper, only after _an heavenly and spiritual manner_.  And the means whereby the body of Christ is received and eaten in the Supper is faith."  (Reformed Episcopals the same in substance.)

5.  The _Presbyterians_ say:  "Worthy receivers, outwardly partaking of the visible elements in this Sacrament, do then also inwardly by faith, really and indeed, yet not carnally and corporally, but spiritually, receive and feed upon Christ crucified, and all benefits of His death:  the body and blood of Christ being there not corporally or carnally in, with, or under the bread and wine; yet as really, but spiritually, present to the faith of believers in that ordinance, as the elements themselves are to their outward senses." -- _Westm. Conf._, Art. XXIX, 7.

6.  The _Methodist Episcopal Church_ in its _Articles of Religion_, Art. XVIII, is one with the Episcopalians.  The _Baptist\index{Baptists}_ and _Congregationalist\index{Congregationalists}_ position is that of the _Westminster Confession_.  

\begin{center}
\textsl{But God says:--}
\end{center}

Matt. 26, 26-28:  "Jesus took bread, and blessed it, and brake it, and gave it to the disciples, and said, Take, eat:  _this is My body_.  And He took the cup, and gave thanks, and gave it to them, saying, Drink ye all of it:  _For this is My blood_ of the New Testament, which is shed for many for the remission of sins."  

1 Cor. 10, 16:  "The cup of blessing which we bless, is it not _the communion of the blood of Christ?_  The bread which we break, is it not _the communion of the body of Christ?_"

1 Cor. 11, 27:  "Wherefore whosoever shall eat this bread, and drink this cup of the Lord, unworthily, shall be _guilty of the body and blood of the Lord_."  (Cf. v. 29.)

Matt. 27, 20:  "Lo, I am with you alway, even unto the end of the world."

\textsc{Note. --} When the Reformed deny the real presence in the Lord's Supper and say that Christ is only _spiritually present_, how can they explain the situation at the _first_ Communion?  At that time the participants did not need to "soar to heaven on the wings of faith" to get His blessing.  The Savior was bodily and spiritually right in the midst of them.  But they received a blessing, surely, and that was what it can only be if Christ meant what He said, His body and blood, for the remission of sins.

\begin{center}
\textsl{2.  What Benefits Do Christians Derive from the Lord's Supper?}

\textsc{Bible Doctrine.}
\end{center}

The Lord's Supper, being a means of grace, confers upon the believing partaker forgiveness fo sins, life, and salvation.

Matt. 26, 28:  "For this is My blood of the New Testament, which is shed for many _for the remission of sins_."  (Luke 22, 19. 20.)

1 Cor. 11, 29:  "The _unworthy_ partaker "eateth and drinketh damnation to himself."  Hence, the _worthy partaker_ must get "forgiveness of sins, life, and salvation."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"We have briefly considered the first part, namely, the essence of this Sacrament.  We now come to its power and blessing, which is a most important part, as we should know what we go for, and what we receive.  This is plainly evident from the words just quoted:  'This is My body and blood, given and shed for you for the remission of sins.'  In other words, we go to the Communion because we receive there a treasure through and in which we obtain the forgiveness of sins.  How so?  There stand the words through which this is imparted!  When He bids me go to eat and to drink, it is with the intent that it should be mine, and be a source of blessing to me as a pledge and earnest thereof, yea, as the very gift in which I am to find shelter against sin, death, and every misfortune." -- Luther's _Large Cat._, V, 20 f.; Lenker's Tr.

\begin{center}
\textsc{Error.}
\end{center}

1.  As the _Reformed Churches_ deny the real presence in the Lord's Supper, so they also deny the real benefit thereof.  But this makes it a Sacrament in name only.  _Presbyterians_, _Congregationalists\index{Congregationalists}_, and _Baptists\index{Baptists}_ unite in confessing that "The Lord Jesus instituted the Sacrament of His body and blood...for the perpetual _remembrance_ of the sacrifice of Himself in His death," etc. -- _Westm. Conf._, XXIX, 1.

2.  The _Methodists_ speak ambiguously in their _Articles of Religion_ of the Lord's Supper.  (Cf. XVI and XVIII.  And what is memant by the following declaration:  "The Supper of the Lord...is a Sacrament of our redemption by Christ's death"?)  But they are unmistakably Reformed in practise and public teaching.  Dr. W. Nast has the following in his _Smaller German Catechism_:  "What does the Lord's Supper signify?  It is to the believer a _memorial feast_ of Christ's atoning passion and death and a _token_ of his participation in the benefits of Christ."  

\textsc{Note 1. --} No Christian dogma has a larger literature to its credit than the Lord's Supper.  The theologians of the early Church as a whole, decidedly taught the real presence; but their lack of precision, at times, has given fanatics and Romanists arguments for the defense of their own strange opinions concerning the Sacrament of the Altar.  

Like Popery itself, the present doctrine of the Lord's Supper in the Catholic Church is a rather late development.  In 844, the French monk Paschasius Radbertus published a work wherein the change of bread and wine into the flesh and blood of Christ was vigorously defended (metabolism, transubstantiation).  In 1214, at the Fourth Lateran Council, this unscriptural opinion was made the doctrine of the Church (reiterated at the Council of Trent, in 1551); and in 1415, at the Council of Constance (where John Hus was burned), it was finally decreed that the consecrated _bread alone_ should be distributed to the lay people (concomitance), the wine to be drunk by the officiating priest, to insure against any of the "precious drops" being spilled in any manner!  And finally, the consecrated elements are sacrificed as a "bloodless offering," espeically for the dead in purgatory by being elevated in the mass; or the consecrated wafer is carried about in solemn procession to be _worshipped_ by the populace. 

These abuses were soon discarded by the Reformers (_Augsb. Conf._, XXIV) but not all reverted to apostolic practise.  Zwingli and Calvin\index{Calvin} differ somewhat in their definitions of the Sacrament of the Altar, but _agree_ in denying the real presence.  And their _chief_ reason for doing so is the rationalistic argument:  human reason cannot understand the real presence of Christ's body and blood in the Sacrament.

\textsc{Note 2. --} Reformed writers on the Lord's Supper generally call the Lutheran doctrine of the real presence "consubstantiation\index{Consubstantiation}."  This term means, "of the same substance," _viz._, that in the Sacrament the bread and the body of Christ form one substance.  Those who apply the term "consubstantiation" to the Lutheran doctrine of the Lord's Supper misprepresent our position.  We do not teach that the bread and the body of Christ, or the wine and His blood, form one substance, but that in, with, and under the bread we receive, not in a natural, but supernatural (sacramental) manner, the true body of Christ, and with the wine His true blood.  This is the plain doctrine of Scripture, though too deep for human reason to fathom.

\begin{center}
\textsc{A Few Objections Answered.}
\end{center}

_First Objection._ -- The word "is," in the words of institution, must be taken to mean "_signifies_."

_Answer._ -- The words of institution are alike wherever quoted.  If any figurative sense were intended, some author would surely have mentioned it.  If the words of institution are to be understood figuratively, then no scripture can be taken literally.  For no doctrine is more plainly stated than that of the Lord's Supper.

Some texts quoted by Reformed writers to support their doctrine that "is" may mean "signifies" prove the contrary:  John 14, 6:  "I am the Way, the Truth and the LIfe"; 10, 9:  "I am the Door."  Here Christ does not _signify_ these things, but He verily _is_ what He claims to be.

It is agreed on every hand that the Old Testament paschal lamb has been superseded by the Lord's Supper.  This lamb signified Christ, who as a Lamb should be sacrificed for the sin of the whole world.  (John 1, 29.)  Now that Christ has come, "signifies" has been, yeah, _must_ be, superseded by "is."  As the body is more than the shadow, so the Eucharist is more than the paschal lamb.

_Second Objection._ -- As Christ's body has ascended into heaven, His presence in the Eucharist can be only spiritual.

_Answer._ -- Though Christ ascended into heaven, this does not prevent him from being present in the Eucharist.  First:  He is almighty, and can do whatsoever He pleases.  Secondly:  He is truthful.  He has promised to be present, and He surely will.  (1 Cor. 10, 16.)  Thirdly:  He is everywhere present.  The right hand of God is everywhere, so Christ also is everywhere.  Fourthly:  Though Christ is invisible, His presence since the incarnation is always real.  Or does he leave His body at the right hand of the Father while He is present spiritually somewhere?  No!  His presence is the presence of the _personal, undivided God-man_.  

To partake of Christ spiritually is to believe on Him.  Of this partaking Christ speaks in John 6.  Zwingli, and the Reformed generally, use this chapter to prove their side of the case.  But how can Jesus there refer to the Sacrament, which was not yet instituted?  Besides, 1 Cor. 11, 27-29 forbids us to bleieve that there is only a spiritual body, a spiritual eating and drinking, in the Lord's Supper, since according to this chapter even unbelievers partake of Him.  

_Third Objection._ -- The body of Christ cannot be present in the Eucharist because it has not the required attribute of omnipresence.  

_Answer._ -- Christ's body participates in the attributes of the divine nature.  He endured fasting forty days and forty nights (Matt. 4, 2); did not sink in the water (Matt. 14, 22); became invisible when the Jews counseled murder (John 8, 59); came out of the sealed grave; was visible and, in an instant, invisible (John 20, 14 f.); came through closed doors (John 20, 19. 26).  Christ's human nature also participates in the attribute of omnipresence.  According to His last will and testament, in which He has expressed Himself clearly and fully concerning our heritage, we believe in the real presence of His body and blood in the sacrament.

\textsc{Note. --} The Reformed insist on breaking the bread at Communion, 1) because Christ did so at the Last Supper; and 2) because it signifies the sufferings which Christ had to undergo in order to redeem us.  We do not hold that this breaking of the bread is essential.  Christ broke the bread because the loaves were too large for the purpose in view; and there is no special significance connected with the act.  He certainly did not break the bread in order to signify the treatment He was to receive; for the Scriptures state explicitly that His body _must not be broken_ (John 19, 63), and the bones of the paschal lamb were not broken (Ex. 12, 46).

When the Lutheran Church uses unleavened wafers at Communion, it does so because they are convenient to distribute, and because the bread used by Christ was unleavened.  In like manner it also uses _grape-wine_, not -juice, nor a juice of some other fruit, or merely water, as some temperance fanatics prescribe, because this was the wine of the Passover, and because Christ explicitly mentions "the fruit of the vine" (Matt. 26, 29) as the proper element.  

## After Death\index{Death, Life after}
\begin{center}
\textsc{Bible Doctrine.}
\end{center}

At death the soul enters on its eternal existence:  bliss or torment.  OF this the body will also partake after Judgement Day.

Gen. 3, 19:  "In the sweat of thy face shalt thou eat bread, till thou return unto the ground, for out of it wast thou taken; for dust thou art, and unto dust shalt thou return."

Eccl. 12, 7:  "Then shall the dust return to the earth as it was; and the spirit shall return unto God, who gave it."

Luke 23, 43:  "To-day thou shalt be with Me in paradise."

Luke 16, 22. 23:  "And it came to pass that the beggar died, and was carried by the angels into Abraham's bosom.  The rich man also died, and was buried; and in hell he lift up his eyes, being in torment."

Rev. 14, 13:  "Blessed are the dead which die in the Lord from henceforth; yea, saith the Spirit, that they may rest from their labors; and their works do follow them."

Heb. 9, 27:  "It is appointed unto men once to die, but after this the Judgement."

Phil. 1, 23:  "I desire to depart, and _to be with Christ_, which is far better."

Acts 1, 25:  "Judas by transgression fell that he might go to _his own place_."

\begin{center}
\textsl{Lutheran Testimony:--}
\end{center}

"I believe in Jesus Christ,...who ascended into heaven, and sitteth on the right hand of God the Father Almighty; from thence He shall come again to judge the quick and the dead." -- _Apostles' Creed_, Sec. Art.  _Athanasian Creed_, § 37.  _Augsb. Conf._, Arts. III and XVII.  

"We pray in this petition...that when, at last, the hour of death shall arrive (He would) grant us a happy end, and graciously take us from this world of sorrow to Himself in heaven." -- _Small Cat._, III, 7.

\begin{center}
\textsc{Error.}
\end{center}

1.  The _Catholic Church_ teaches that "there exists in the next life a middle state of temporary punishment, allotted for those who have died in venial sin, or who have not satisfied the justice of God for sins already forgiven.... This intermediate state is commonly called purgatory."  (Gibbons, _Faith of Our Fathers_, p. 248.)  This declaration is substantially the same as that contained in canon 30, session 6, of the Council of Trent, and in question 3, part I, 6, of the _Roman Catechism_. -- When the cardinal says that the doctrine of purgatory "is clearly taught in the Old Testament; that it is, at least, insinuated in the New Testament; that it is unanimously proclaimed by the Fathers of the Church," but includes in the Old Testament the apocryphal books of the Maccabees (see 2 Macc. 12, 43-46), and mentions that the Monatist Tertullian, A. D. 160-220, as the first testifying "Father," his "clear" and "unanimous" proofs do not appear convincing.

2.  Though the representative _Reformed_ Churches stand for retribution in their confessions, the prevailing opinion among their members is that "we get all the hell there is here on earth."  Such as opinion is not even _rationalism_.  The conception of a just God forbids it.  Yet the REformed sects in their preaching and in their literature very generally ignore the Bible-doctrine concerning a state of punishment after death.

Lodgism is to a great extent the cause for disbelief in eternal punishment.  Every lodge-man buried, even a suicide or a profligate Elk, is declared saved, "removed to the Grand Lodge above" or to "the happy hunting-ground" of the Red Man.

\begin{center}
\textsl{But God says:--}
\end{center}

2 Cor. 5, 10:  "We must all appear before the judgment-seat of Christ, that every one may receive the things done in his body, according to that he hath done, whether it be good or bad."  (1 Cor. 15.)

Dan. 12, 2:  "And many of them that sleep in the dust of the earth shall awake, some to everlastin life and some to shame and everlasting contempt."

Rom. 14, 10:  "We shall all stand before the judgment-seat of Christ."

Matt. 25, 41. 46:  "Then shall He say unto them on the left hand:  Depart from Me, ye cursed, into everlasting fire, prepared for the devil and his angels.  And these shall go away into everlasting punishment, but the righteous into life eternal."


