---
title:  'The Difference'
subtitle:  'A Popular Guide to Denominational History and Doctrine'
author:  'I.G. Monson'
date:  '1915'
documentclass:  book
---

# Preface {.unlisted .unnumbered}
What is the difference between the various Christian sects?  The common answer is that there is no difference, that they all have the same Bible, that all are trying to reach the same place, etc.  For the ignorant this is the easiest way to get away from this question.  The lazy, indifferent, and the unbeliever will find the same answer the most convenient.  But any one interested in truth and in Christianity will gladly accept information concerning the most important questions in life.

Of the many good works on the subject none are suited for general distribution among the several Lutheran church-bodies in this country.  In the theological seminaries the works of Winer, Guericke, Guenther, and Gumlich are, of course, indispensible; but in the preparatory schools, parochial and Sunday-schools, as well as in the average Lutheran home, such learned works are impractical, if not wholly useless.

The aim has, therefore, been in the present volume to be more suggestive than exhaustive, to avoid all technicalities, and to treat the different dogmas in such a manner that the common, every-day Christian could understand them.

In order to attin this end, the dogmatic, positive, Biblical, Lutheran method was found most serviceable.  And for this we make no apology, the cry of "represtination of Reformation theology" by rationalists and unionists to the contrary notwithstanding.  As God at the last day will judge man according to His Word (John 12, 48), the only right way is to ask for the Old Paths, where is the good way, and walk therein (Jer. 6, 16).

Now and then names and phrases will be found inclosed in brackets.  This has been done in order to stimulate further research by both teacher and student.  Books of reference of some kind are now in nearly every home.

To write on Symbolism in our unionistic and irreligious age is, indeed, a thankless task.  And yet _the full truth was never popular_.  Now more than in the last century the words of Stahl have full force:  "The powers that be are against us.  the masses are against us.  The tendency of the times is against us.  The powerful errorists within the Church are against us."  To this may here be added:  The Reformed civilization under which we live is against us.

But God has a remnant yet to save.  _And it will be saved, but only through the Word of Truth_.

\textsc{The Author.}


